package io.exoreaction.synthesis.skills;

import io.exoreaction.synthesis.org.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Path;
import java.time.Instant;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for {@link SkillTemplate} YAML generation.
 */
class SkillTemplateTest {

    @TempDir
    Path tempDir;

    private static final Instant TIMESTAMP = Instant.parse("2026-02-14T12:00:00Z");

    // --- Workspace context ---

    @Test
    void workspaceContext_generatesValidYaml() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);

        String yaml = SkillTemplate.workspaceContext("My Workspace", tempDir,
                List.of(org), TIMESTAMP);

        assertTrue(yaml.startsWith("name: workspace-context\n"));
        assertTrue(yaml.contains("version: 1.0.0"));
        assertTrue(yaml.contains("auto_load: true"));
        assertTrue(yaml.contains("instructions: |"));
    }

    @Test
    void workspaceContext_includesWorkspaceName() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);

        String yaml = SkillTemplate.workspaceContext("My Workspace", tempDir,
                List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("My Workspace"));
        assertTrue(yaml.contains(tempDir.toString()));
    }

    @Test
    void workspaceContext_listsAllOrganizations() {
        Organization org1 = createOrg("OrgA", OrganizationType.COMPANY);
        Organization org2 = createOrg("OrgB", OrganizationType.FOUNDATION);

        String yaml = SkillTemplate.workspaceContext("Test", tempDir,
                List.of(org1, org2), TIMESTAMP);

        assertTrue(yaml.contains("OrgA"));
        assertTrue(yaml.contains("OrgB"));
        assertTrue(yaml.contains("Organizations (2)"));
    }

    @Test
    void workspaceContext_includesClientAndProductCounts() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addClient(new Client("ClientA", "TestCo", tempDir.resolve("a"),
                ClientStatus.ACTIVE, "ClientA"));
        org.addProduct(new Product("ProductX", "TestCo", tempDir.resolve("b")));

        String yaml = SkillTemplate.workspaceContext("Test", tempDir,
                List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("Total clients: 1"));
        assertTrue(yaml.contains("Total products: 1"));
    }

    @Test
    void workspaceContext_includesTimestamp() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);

        String yaml = SkillTemplate.workspaceContext("Test", tempDir,
                List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("auto-generated by Synthesis"));
        assertTrue(yaml.contains("2026"));
    }

    // --- Organization context ---

    @Test
    void organizationContext_generatesValidYaml() {
        Organization org = createOrg("eXOReaction", OrganizationType.COMPANY);

        String yaml = SkillTemplate.organizationContext(org, TIMESTAMP);

        assertTrue(yaml.startsWith("name: organization-exoreaction\n"));
        assertTrue(yaml.contains("version: 1.0.0"));
        assertTrue(yaml.contains("instructions: |"));
    }

    @Test
    void organizationContext_includesOrgDetails() {
        Organization org = createOrg("eXOReaction", OrganizationType.COMPANY);
        org.setDescription("AI consulting company");

        String yaml = SkillTemplate.organizationContext(org, TIMESTAMP);

        assertTrue(yaml.contains("eXOReaction"));
        assertTrue(yaml.contains("COMPANY"));
        assertTrue(yaml.contains("AI consulting company"));
    }

    @Test
    void organizationContext_groupsClientsByStatus() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addClient(new Client("ActiveClient", "TestCo",
                tempDir.resolve("a"), ClientStatus.ACTIVE, "ActiveClient"));
        org.addClient(new Client("OpportunityClient", "TestCo",
                tempDir.resolve("b"), ClientStatus.OPPORTUNITY, "opportunity-Client"));
        org.addClient(new Client("PastClient", "TestCo",
                tempDir.resolve("c"), ClientStatus.PAST, "PastClient-past"));

        String yaml = SkillTemplate.organizationContext(org, TIMESTAMP);

        assertTrue(yaml.contains("Active Clients (1)"));
        assertTrue(yaml.contains("ActiveClient"));
        assertTrue(yaml.contains("Opportunity Clients (1)"));
        assertTrue(yaml.contains("OpportunityClient"));
        assertTrue(yaml.contains("Past Clients (1)"));
        assertTrue(yaml.contains("PastClient"));
    }

    @Test
    void organizationContext_includesProducts() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addProduct(new Product("product-alpha", "TestCo", tempDir.resolve("p")));

        String yaml = SkillTemplate.organizationContext(org, TIMESTAMP);

        assertTrue(yaml.contains("Products (1)"));
        assertTrue(yaml.contains("product-alpha"));
    }

    @Test
    void organizationContext_includesCodebasePaths() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.getCodebasePaths().add("/src/testco/main-repo/");

        String yaml = SkillTemplate.organizationContext(org, TIMESTAMP);

        assertTrue(yaml.contains("Codebase Paths"));
        assertTrue(yaml.contains("/src/testco/main-repo/"));
    }

    // --- Navigate clients ---

    @Test
    void navigateClients_generatesValidYaml() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addClient(new Client("Acme", "TestCo",
                tempDir.resolve("acme"), ClientStatus.ACTIVE, "Acme"));

        String yaml = SkillTemplate.navigateClients(List.of(org), TIMESTAMP);

        assertTrue(yaml.startsWith("name: navigate-clients\n"));
        assertTrue(yaml.contains("Acme"));
        assertTrue(yaml.contains(tempDir.resolve("acme").toString()));
    }

    @Test
    void navigateClients_organizesbyOrg() {
        Organization org1 = createOrg("OrgA", OrganizationType.COMPANY);
        org1.addClient(new Client("ClientX", "OrgA",
                tempDir.resolve("x"), ClientStatus.ACTIVE, "ClientX"));

        Organization org2 = createOrg("OrgB", OrganizationType.COMPANY);
        org2.addClient(new Client("ClientY", "OrgB",
                tempDir.resolve("y"), ClientStatus.ACTIVE, "ClientY"));

        String yaml = SkillTemplate.navigateClients(List.of(org1, org2), TIMESTAMP);

        assertTrue(yaml.contains("OrgA Clients"));
        assertTrue(yaml.contains("ClientX"));
        assertTrue(yaml.contains("OrgB Clients"));
        assertTrue(yaml.contains("ClientY"));
    }

    // --- Pipeline tracker ---

    @Test
    void pipelineTracker_generatesValidYaml() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addClient(new Client("Acme", "TestCo",
                tempDir.resolve("a"), ClientStatus.ACTIVE, "Acme"));

        String yaml = SkillTemplate.pipelineTracker(List.of(org), TIMESTAMP);

        assertTrue(yaml.startsWith("name: pipeline-tracker\n"));
        assertTrue(yaml.contains("Business Pipeline"));
    }

    @Test
    void pipelineTracker_groupsByStatus() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addClient(new Client("SignedClient", "TestCo",
                tempDir.resolve("s"), ClientStatus.SIGNED, "SignedClient"));
        org.addClient(new Client("ActiveClient", "TestCo",
                tempDir.resolve("a"), ClientStatus.ACTIVE, "ActiveClient"));
        org.addClient(new Client("OppClient", "TestCo",
                tempDir.resolve("o"), ClientStatus.OPPORTUNITY, "opportunity-OppClient"));

        String yaml = SkillTemplate.pipelineTracker(List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("Signed (1)"));
        assertTrue(yaml.contains("Active (1)"));
        assertTrue(yaml.contains("Opportunities (1)"));
    }

    // --- Proof points ---

    @Test
    void proofPoints_generatesValidYaml() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addProduct(new Product("lib-pcb", "TestCo", tempDir.resolve("pcb")));

        String yaml = SkillTemplate.proofPoints(List.of(org), TIMESTAMP);

        assertTrue(yaml.startsWith("name: proof-points\n"));
        assertTrue(yaml.contains("Technical Proof Points"));
        assertTrue(yaml.contains("lib-pcb"));
    }

    @Test
    void proofPoints_includesCodebasePaths() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.getCodebasePaths().add("/src/test/repo/");

        String yaml = SkillTemplate.proofPoints(List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("/src/test/repo/"));
    }

    // --- Utility methods ---

    @Test
    void sanitizeForFilename_lowercases() {
        assertEquals("exoreaction", SkillTemplate.sanitizeForFilename("eXOReaction"));
    }

    @Test
    void sanitizeForFilename_replacesSpecialChars() {
        assertEquals("t-hex", SkillTemplate.sanitizeForFilename("T-Hex"));
    }

    @Test
    void sanitizeForFilename_replacesSpaces() {
        assertEquals("my-company", SkillTemplate.sanitizeForFilename("My Company"));
    }

    @Test
    void sanitizeForFilename_collapsesMultipleHyphens() {
        assertEquals("a-b", SkillTemplate.sanitizeForFilename("a--b"));
    }

    @Test
    void yamlHeader_formatsCorrectly() {
        String header = SkillTemplate.yamlHeader("test-skill", "A test skill");
        assertTrue(header.contains("name: test-skill"));
        assertTrue(header.contains("version: 1.0.0"));
        assertTrue(header.contains("description: A test skill"));
        assertTrue(header.contains("auto_load: true"));
    }

    @Test
    void formatInstructions_indentsCorrectly() {
        String result = SkillTemplate.formatInstructions("Line 1\nLine 2\n\nLine 4");
        assertTrue(result.startsWith("instructions: |\n"));
        assertTrue(result.contains("  Line 1\n"));
        assertTrue(result.contains("  Line 2\n"));
        assertTrue(result.contains("\n\n"));
        assertTrue(result.contains("  Line 4\n"));
    }

    // --- Helper ---

    private Organization createOrg(String name, OrganizationType type) {
        return new Organization(name, type, tempDir.resolve(name));
    }
}
