package io.exoreaction.synthesis.skills;

import io.exoreaction.synthesis.org.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for {@link SkillTemplate} YAML generation.
 */
class SkillTemplateTest {

    @TempDir
    Path tempDir;

    private static final Instant TIMESTAMP = Instant.parse("2026-02-14T12:00:00Z");

    // --- Workspace context ---

    @Test
    void workspaceContext_generatesValidYaml() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);

        String yaml = SkillTemplate.workspaceContext("My Workspace", tempDir,
                List.of(org), TIMESTAMP);

        assertTrue(yaml.startsWith("name: workspace-context\n"));
        assertTrue(yaml.contains("version: 1.0.0"));
        assertTrue(yaml.contains("auto_load: true"));
        assertTrue(yaml.contains("instructions: |"));
    }

    @Test
    void workspaceContext_includesWorkspaceName() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);

        String yaml = SkillTemplate.workspaceContext("My Workspace", tempDir,
                List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("My Workspace"));
        assertTrue(yaml.contains(tempDir.toString()));
    }

    @Test
    void workspaceContext_listsAllOrganizations() {
        Organization org1 = createOrg("OrgA", OrganizationType.COMPANY);
        Organization org2 = createOrg("OrgB", OrganizationType.FOUNDATION);

        String yaml = SkillTemplate.workspaceContext("Test", tempDir,
                List.of(org1, org2), TIMESTAMP);

        assertTrue(yaml.contains("OrgA"));
        assertTrue(yaml.contains("OrgB"));
        assertTrue(yaml.contains("Organizations (2)"));
    }

    @Test
    void workspaceContext_includesClientAndProductCounts() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addClient(new Client("ClientA", "TestCo", tempDir.resolve("a"),
                ClientStatus.ACTIVE, "ClientA"));
        org.addProduct(new Product("ProductX", "TestCo", tempDir.resolve("b")));

        String yaml = SkillTemplate.workspaceContext("Test", tempDir,
                List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("Total clients: 1"));
        assertTrue(yaml.contains("Total products: 1"));
    }

    @Test
    void workspaceContext_includesTimestamp() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);

        String yaml = SkillTemplate.workspaceContext("Test", tempDir,
                List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("auto-generated by Synthesis"));
        assertTrue(yaml.contains("2026"));
    }

    // --- Organization context ---

    @Test
    void organizationContext_generatesValidYaml() {
        Organization org = createOrg("eXOReaction", OrganizationType.COMPANY);

        String yaml = SkillTemplate.organizationContext(org, TIMESTAMP);

        assertTrue(yaml.startsWith("name: organization-exoreaction\n"));
        assertTrue(yaml.contains("version: 1.0.0"));
        assertTrue(yaml.contains("instructions: |"));
    }

    @Test
    void organizationContext_includesOrgDetails() {
        Organization org = createOrg("eXOReaction", OrganizationType.COMPANY);
        org.setDescription("AI consulting company");

        String yaml = SkillTemplate.organizationContext(org, TIMESTAMP);

        assertTrue(yaml.contains("eXOReaction"));
        assertTrue(yaml.contains("COMPANY"));
        assertTrue(yaml.contains("AI consulting company"));
    }

    @Test
    void organizationContext_groupsClientsByStatus() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addClient(new Client("ActiveClient", "TestCo",
                tempDir.resolve("a"), ClientStatus.ACTIVE, "ActiveClient"));
        org.addClient(new Client("OpportunityClient", "TestCo",
                tempDir.resolve("b"), ClientStatus.OPPORTUNITY, "opportunity-Client"));
        org.addClient(new Client("PastClient", "TestCo",
                tempDir.resolve("c"), ClientStatus.PAST, "PastClient-past"));

        String yaml = SkillTemplate.organizationContext(org, TIMESTAMP);

        assertTrue(yaml.contains("Active Clients (1)"));
        assertTrue(yaml.contains("ActiveClient"));
        assertTrue(yaml.contains("Opportunity Clients (1)"));
        assertTrue(yaml.contains("OpportunityClient"));
        assertTrue(yaml.contains("Past Clients (1)"));
        assertTrue(yaml.contains("PastClient"));
    }

    @Test
    void organizationContext_includesProducts() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addProduct(new Product("product-alpha", "TestCo", tempDir.resolve("p")));

        String yaml = SkillTemplate.organizationContext(org, TIMESTAMP);

        assertTrue(yaml.contains("Products (1)"));
        assertTrue(yaml.contains("product-alpha"));
    }

    @Test
    void organizationContext_includesCodebasePaths() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.getCodebasePaths().add("/src/testco/main-repo/");

        String yaml = SkillTemplate.organizationContext(org, TIMESTAMP);

        assertTrue(yaml.contains("Codebase Paths"));
        assertTrue(yaml.contains("/src/testco/main-repo/"));
    }

    // --- Navigate clients ---

    @Test
    void navigateClients_generatesValidYaml() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addClient(new Client("Acme", "TestCo",
                tempDir.resolve("acme"), ClientStatus.ACTIVE, "Acme"));

        String yaml = SkillTemplate.navigateClients(List.of(org), TIMESTAMP);

        assertTrue(yaml.startsWith("name: navigate-clients\n"));
        assertTrue(yaml.contains("Acme"));
        assertTrue(yaml.contains(tempDir.resolve("acme").toString()));
    }

    @Test
    void navigateClients_organizesbyOrg() {
        Organization org1 = createOrg("OrgA", OrganizationType.COMPANY);
        org1.addClient(new Client("ClientX", "OrgA",
                tempDir.resolve("x"), ClientStatus.ACTIVE, "ClientX"));

        Organization org2 = createOrg("OrgB", OrganizationType.COMPANY);
        org2.addClient(new Client("ClientY", "OrgB",
                tempDir.resolve("y"), ClientStatus.ACTIVE, "ClientY"));

        String yaml = SkillTemplate.navigateClients(List.of(org1, org2), TIMESTAMP);

        assertTrue(yaml.contains("OrgA Clients"));
        assertTrue(yaml.contains("ClientX"));
        assertTrue(yaml.contains("OrgB Clients"));
        assertTrue(yaml.contains("ClientY"));
    }

    // --- Pipeline tracker ---

    @Test
    void pipelineTracker_generatesValidYaml() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addClient(new Client("Acme", "TestCo",
                tempDir.resolve("a"), ClientStatus.ACTIVE, "Acme"));

        String yaml = SkillTemplate.pipelineTracker(List.of(org), TIMESTAMP);

        assertTrue(yaml.startsWith("name: pipeline-tracker\n"));
        assertTrue(yaml.contains("Business Pipeline"));
    }

    @Test
    void pipelineTracker_groupsByStatus() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addClient(new Client("SignedClient", "TestCo",
                tempDir.resolve("s"), ClientStatus.SIGNED, "SignedClient"));
        org.addClient(new Client("ActiveClient", "TestCo",
                tempDir.resolve("a"), ClientStatus.ACTIVE, "ActiveClient"));
        org.addClient(new Client("OppClient", "TestCo",
                tempDir.resolve("o"), ClientStatus.OPPORTUNITY, "opportunity-OppClient"));

        String yaml = SkillTemplate.pipelineTracker(List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("Signed (1)"));
        assertTrue(yaml.contains("Active (1)"));
        assertTrue(yaml.contains("Opportunities (1)"));
    }

    // --- Proof points ---

    @Test
    void proofPoints_generatesValidYaml() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addProduct(new Product("lib-pcb", "TestCo", tempDir.resolve("pcb")));

        String yaml = SkillTemplate.proofPoints(List.of(org), TIMESTAMP);

        assertTrue(yaml.startsWith("name: proof-points\n"));
        assertTrue(yaml.contains("Technical Proof Points"));
        assertTrue(yaml.contains("lib-pcb"));
    }

    @Test
    void proofPoints_includesCodebasePaths() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.getCodebasePaths().add("/src/test/repo/");

        String yaml = SkillTemplate.proofPoints(List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("/src/test/repo/"));
    }

    // --- Architecture overview ---

    @Test
    void architectureOverview_generatesValidYaml() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addProduct(new Product("lib-pcb", "TestCo", tempDir.resolve("pcb")));
        org.getCodebasePaths().add("/src/testco/main-repo/");

        String yaml = SkillTemplate.architectureOverview(List.of(org), TIMESTAMP);

        assertTrue(yaml.startsWith("name: architecture-overview\n"));
        assertTrue(yaml.contains("version: 1.0.0"));
        assertTrue(yaml.contains("auto_load: true"));
        assertTrue(yaml.contains("instructions: |"));
    }

    @Test
    void architectureOverview_includesProductsAsComponents() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.addProduct(new Product("product-alpha", "TestCo", tempDir.resolve("alpha")));

        String yaml = SkillTemplate.architectureOverview(List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("Components:"));
        assertTrue(yaml.contains("product-alpha"));
    }

    @Test
    void architectureOverview_includesCodebasesAsRepositories() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);
        org.getCodebasePaths().add("/src/testco/repo/");

        String yaml = SkillTemplate.architectureOverview(List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("Source Repositories:"));
        assertTrue(yaml.contains("/src/testco/repo/"));
    }

    @Test
    void architectureOverview_skipsEmptyOrgs() {
        Organization empty = createOrg("EmptyCo", OrganizationType.COMPANY);
        Organization withProducts = createOrg("ActiveCo", OrganizationType.COMPANY);
        withProducts.addProduct(new Product("prod", "ActiveCo", tempDir.resolve("p")));

        String yaml = SkillTemplate.architectureOverview(
                List.of(empty, withProducts), TIMESTAMP);

        assertFalse(yaml.contains("EmptyCo"));
        assertTrue(yaml.contains("ActiveCo"));
    }

    @Test
    void architectureOverview_truncatesLongCodebaseLists() {
        Organization org = createOrg("BigCo", OrganizationType.COMPANY);
        for (int i = 0; i < 15; i++) {
            org.getCodebasePaths().add("/src/repo-" + i + "/");
        }

        String yaml = SkillTemplate.architectureOverview(List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("(+5 more)"));
    }

    // --- Tech stack ---

    @Test
    void techStack_generatesValidYaml() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);

        String yaml = SkillTemplate.techStack(List.of(org), tempDir, TIMESTAMP);

        assertTrue(yaml.startsWith("name: tech-stack\n"));
        assertTrue(yaml.contains("version: 1.0.0"));
        assertTrue(yaml.contains("instructions: |"));
    }

    @Test
    void techStack_detectsMavenJava() throws IOException {
        Organization org = createOrg("JavaCo", OrganizationType.COMPANY);
        java.nio.file.Path orgDir = tempDir.resolve("JavaCo");
        Files.createDirectories(orgDir);
        Files.writeString(orgDir.resolve("pom.xml"), "<project/>");

        String yaml = SkillTemplate.techStack(List.of(org), tempDir, TIMESTAMP);

        assertTrue(yaml.contains("Java (Maven)"));
    }

    @Test
    void techStack_detectsNodeJs() throws IOException {
        Organization org = createOrg("JsCo", OrganizationType.COMPANY);
        java.nio.file.Path orgDir = tempDir.resolve("JsCo");
        Files.createDirectories(orgDir);
        Files.writeString(orgDir.resolve("package.json"), "{}");

        String yaml = SkillTemplate.techStack(List.of(org), tempDir, TIMESTAMP);

        assertTrue(yaml.contains("JavaScript/TypeScript (Node.js)"));
    }

    @Test
    void techStack_showsNoTechWhenNoneDetected() {
        Organization org = createOrg("EmptyCo", OrganizationType.COMPANY);

        String yaml = SkillTemplate.techStack(List.of(org), tempDir, TIMESTAMP);

        assertTrue(yaml.contains("No technology indicators detected"));
    }

    // --- Key decisions ---

    @Test
    void keyDecisions_generatesValidYaml() {
        Organization org = createOrg("TestCo", OrganizationType.COMPANY);

        String yaml = SkillTemplate.keyDecisions(List.of(org), TIMESTAMP);

        assertTrue(yaml.startsWith("name: key-decisions\n"));
        assertTrue(yaml.contains("version: 1.0.0"));
        assertTrue(yaml.contains("instructions: |"));
    }

    @Test
    void keyDecisions_findsStrategyDirectory() throws IOException {
        Organization org = createOrg("StrategicCo", OrganizationType.COMPANY);
        java.nio.file.Path orgDir = tempDir.resolve("StrategicCo");
        Files.createDirectories(orgDir.resolve("business").resolve("strategy"));

        String yaml = SkillTemplate.keyDecisions(List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("StrategicCo"));
        assertTrue(yaml.contains("business" + java.io.File.separator + "strategy"));
    }

    @Test
    void keyDecisions_showsNoRecordsMessage() {
        Organization org = createOrg("NoDocs", OrganizationType.COMPANY);

        String yaml = SkillTemplate.keyDecisions(List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("No formal decision records"));
    }

    @Test
    void keyDecisions_findsAdrDirectory() throws IOException {
        Organization org = createOrg("AdrCo", OrganizationType.COMPANY);
        java.nio.file.Path orgDir = tempDir.resolve("AdrCo");
        Files.createDirectories(orgDir.resolve("docs").resolve("adr"));

        String yaml = SkillTemplate.keyDecisions(List.of(org), TIMESTAMP);

        assertTrue(yaml.contains("AdrCo"));
    }

    // --- Utility methods ---

    @Test
    void sanitizeForFilename_lowercases() {
        assertEquals("exoreaction", SkillTemplate.sanitizeForFilename("eXOReaction"));
    }

    @Test
    void sanitizeForFilename_replacesSpecialChars() {
        assertEquals("t-hex", SkillTemplate.sanitizeForFilename("T-Hex"));
    }

    @Test
    void sanitizeForFilename_replacesSpaces() {
        assertEquals("my-company", SkillTemplate.sanitizeForFilename("My Company"));
    }

    @Test
    void sanitizeForFilename_collapsesMultipleHyphens() {
        assertEquals("a-b", SkillTemplate.sanitizeForFilename("a--b"));
    }

    @Test
    void yamlHeader_formatsCorrectly() {
        String header = SkillTemplate.yamlHeader("test-skill", "A test skill");
        assertTrue(header.contains("name: test-skill"));
        assertTrue(header.contains("version: 1.0.0"));
        assertTrue(header.contains("description: A test skill"));
        assertTrue(header.contains("auto_load: true"));
    }

    @Test
    void formatInstructions_indentsCorrectly() {
        String result = SkillTemplate.formatInstructions("Line 1\nLine 2\n\nLine 4");
        assertTrue(result.startsWith("instructions: |\n"));
        assertTrue(result.contains("  Line 1\n"));
        assertTrue(result.contains("  Line 2\n"));
        assertTrue(result.contains("\n\n"));
        assertTrue(result.contains("  Line 4\n"));
    }

    // --- detectTechnologies ---

    @Test
    void detectTechnologies_emptyOrg_noTech() {
        Organization org = createOrg("Empty", OrganizationType.COMPANY);

        Set<String> tech = SkillTemplate.detectTechnologies(org);

        assertTrue(tech.isEmpty());
    }

    @Test
    void detectTechnologies_mavenProject() throws IOException {
        Organization org = createOrg("JavaProject", OrganizationType.COMPANY);
        java.nio.file.Path orgDir = tempDir.resolve("JavaProject");
        Files.createDirectories(orgDir);
        Files.writeString(orgDir.resolve("pom.xml"), "<project/>");

        Set<String> tech = SkillTemplate.detectTechnologies(org);

        assertTrue(tech.contains("Java (Maven)"));
    }

    @Test
    void detectTechnologies_multiTechProject() throws IOException {
        Organization org = createOrg("FullStack", OrganizationType.COMPANY);
        java.nio.file.Path orgDir = tempDir.resolve("FullStack");
        Files.createDirectories(orgDir);
        Files.writeString(orgDir.resolve("pom.xml"), "<project/>");
        Files.writeString(orgDir.resolve("Dockerfile"), "FROM java:21");

        Set<String> tech = SkillTemplate.detectTechnologies(org);

        assertTrue(tech.contains("Java (Maven)"));
        assertTrue(tech.contains("Docker"));
    }

    // --- MAX_LIST_ITEMS ---

    @Test
    void maxListItems_isReasonableValue() {
        assertTrue(SkillTemplate.MAX_LIST_ITEMS > 0);
        assertTrue(SkillTemplate.MAX_LIST_ITEMS <= 20);
    }

    // --- Helper ---

    private Organization createOrg(String name, OrganizationType type) {
        return new Organization(name, type, tempDir.resolve(name));
    }
}
