package io.exoreaction.synthesis.report;

import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Renders ReportResult into target-specific output formats.
 *
 * <p>Three rendering modes:
 * <ul>
 *   <li>CEO: Actionable executive report with pipeline, activities, decisions</li>
 *   <li>Board: Formal with strategic focus and high-level metrics</li>
 *   <li>Investor: Growth-oriented with traction metrics</li>
 * </ul>
 */
public class ReportRenderer {

    private static final DateTimeFormatter TIMESTAMP_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z")
                    .withZone(ZoneId.systemDefault());

    private ReportRenderer() {}

    /**
     * Renders a ReportResult based on its target type.
     *
     * @param result the report result to render
     * @return formatted markdown output
     */
    public static String render(ReportResult result) {
        if (result == null) return "";

        StringBuilder sb = new StringBuilder();

        // Header
        sb.append("# ").append(result.target().displayName()).append("\n\n");
        sb.append("**Generated:** ").append(formatTimestamp(result.generatedAt())).append("\n");
        sb.append("**Topic:** ").append(result.topic().displayName()).append("\n");
        sb.append("**Period:** ").append(formatPeriod(result.period())).append("\n");
        sb.append("**Model:** ").append(result.model()).append("\n");

        if (result.documents() != null && !result.documents().isEmpty()) {
            sb.append("**Sources:** ").append(result.documents().size()).append(" business documents analyzed\n");
        }

        sb.append("\n---\n\n");

        // Main report body (AI-generated content)
        if (result.finalReport() != null && !result.finalReport().isBlank()) {
            sb.append(result.finalReport()).append("\n\n");
        }

        // Footer with metadata
        sb.append("---\n\n");
        sb.append("*Report generated by Synthesis | ");
        sb.append("Tokens: ").append(String.format("%,d", result.totalTokenCount()));
        sb.append(" | Cost: $").append(String.format("%.4f", result.estimatedCostUsd()));
        if (result.fromCache()) {
            sb.append(" | Source: cache");
        } else if (result.generationTimeMs() > 0) {
            sb.append(" | Time: ").append(result.generationTimeMs()).append("ms");
        }
        sb.append("*\n");

        // Append source document listing
        if (result.documents() != null && !result.documents().isEmpty()) {
            sb.append("\n### Source Documents\n\n");
            for (ReportDocument doc : result.documents()) {
                sb.append("- **").append(doc.category()).append("**: `")
                        .append(doc.relativePath()).append("` (")
                        .append(formatSize(doc.sizeBytes()))
                        .append(", modified ").append(formatTimestamp(doc.lastModified()))
                        .append(")\n");
            }
        }

        return sb.toString();
    }

    /**
     * Formats a period code into human-readable text.
     * Supports dynamic day-based periods (e.g. "5d" = "Last 5 days").
     *
     * @see <a href="https://github.com/exoreaction/Synthesis/issues/250">#250</a>
     */
    public static String formatPeriod(String period) {
        if (period == null) return "Last 7 days";
        // Handle dynamic day-based periods (e.g. "5d", "12d")
        if (period.endsWith("d")) {
            try {
                int days = Integer.parseInt(period.substring(0, period.length() - 1));
                return "Last " + days + " day" + (days != 1 ? "s" : "");
            } catch (NumberFormatException ignored) {
                // Fall through
            }
        }
        return switch (period) {
            case "1w" -> "Last 7 days";
            case "2w" -> "Last 14 days";
            case "1m" -> "Last 30 days";
            default -> period;
        };
    }

    /**
     * Converts a period code to a description for AI prompts.
     * Supports dynamic day-based periods (e.g. "5d").
     *
     * @see <a href="https://github.com/exoreaction/Synthesis/issues/250">#250</a>
     */
    public static String periodToDescription(String period) {
        if (period == null) return "the last 7 days";
        // Handle dynamic day-based periods
        if (period.endsWith("d")) {
            try {
                int days = Integer.parseInt(period.substring(0, period.length() - 1));
                return "the last " + days + " day" + (days != 1 ? "s" : "");
            } catch (NumberFormatException ignored) {
                // Fall through
            }
        }
        return switch (period) {
            case "1w" -> "the last 7 days";
            case "2w" -> "the last 14 days";
            case "1m" -> "the last 30 days";
            default -> "the last 7 days";
        };
    }

    private static String formatTimestamp(Instant instant) {
        if (instant == null) return "N/A";
        return TIMESTAMP_FORMAT.format(instant);
    }

    private static String formatSize(long bytes) {
        if (bytes < 1024) return bytes + " B";
        if (bytes < 1024 * 1024) return String.format("%.1f KB", bytes / 1024.0);
        return String.format("%.1f MB", bytes / (1024.0 * 1024));
    }
}
