package io.exoreaction.synthesis.telemetry;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.UUID;

/**
 * Manages the persistent client UUID for telemetry identification.
 *
 * <p>The UUID is stored globally at {@code ~/.synthesis/client-uuid} so it persists
 * across workspaces and provides a single identity per installation. The UUID is
 * a random v4 UUID with no personally identifiable information.
 *
 * <p>Lifecycle:
 * <ul>
 *   <li>Generated once on first use (or during {@code synthesis init})</li>
 *   <li>Persisted to disk at {@code ~/.synthesis/client-uuid}</li>
 *   <li>Loaded from disk on subsequent runs</li>
 *   <li>Can be regenerated by deleting the file and running any command</li>
 * </ul>
 *
 * <p>Privacy: The UUID is a random identifier with no relation to the user's
 * identity, hostname, MAC address, or any other personally identifiable information.
 */
public final class ClientUUID {

    /** Directory for global Synthesis data (under user home). */
    public static final String GLOBAL_DIR = ".synthesis";

    /** Filename for the client UUID file. */
    public static final String UUID_FILENAME = "client-uuid";

    private ClientUUID() {}

    /**
     * Returns the path to the global client UUID file.
     *
     * @return the path {@code ~/.synthesis/client-uuid}
     */
    public static Path getUuidPath() {
        return Path.of(System.getProperty("user.home")).resolve(GLOBAL_DIR).resolve(UUID_FILENAME);
    }

    /**
     * Returns the path to the global client UUID file using a custom home directory.
     * Useful for testing.
     *
     * @param homeDir the home directory to use instead of {@code user.home}
     * @return the path {@code <homeDir>/.synthesis/client-uuid}
     */
    public static Path getUuidPath(Path homeDir) {
        return homeDir.resolve(GLOBAL_DIR).resolve(UUID_FILENAME);
    }

    /**
     * Gets or creates the client UUID.
     *
     * <p>If the UUID file exists and contains a valid UUID, it is returned.
     * Otherwise, a new UUID is generated, persisted, and returned.
     *
     * @return the client UUID string
     * @throws IOException if the UUID file cannot be read or written
     */
    public static String getOrCreate() throws IOException {
        return getOrCreate(getUuidPath());
    }

    /**
     * Gets or creates the client UUID at a custom path.
     * Useful for testing.
     *
     * @param uuidPath the path to the UUID file
     * @return the client UUID string
     * @throws IOException if the UUID file cannot be read or written
     */
    public static String getOrCreate(Path uuidPath) throws IOException {
        if (Files.exists(uuidPath)) {
            String content = Files.readString(uuidPath).trim();
            if (isValidUuid(content)) {
                return content;
            }
            // Invalid content -- regenerate
        }

        // Generate new UUID
        String uuid = UUID.randomUUID().toString();
        persist(uuidPath, uuid);
        return uuid;
    }

    /**
     * Reads the existing client UUID, if present.
     *
     * @return the UUID string, or null if not yet generated
     */
    public static String read() {
        return read(getUuidPath());
    }

    /**
     * Reads the existing client UUID from a custom path.
     *
     * @param uuidPath the path to the UUID file
     * @return the UUID string, or null if not yet generated or invalid
     */
    public static String read(Path uuidPath) {
        try {
            if (Files.exists(uuidPath)) {
                String content = Files.readString(uuidPath).trim();
                if (isValidUuid(content)) {
                    return content;
                }
            }
        } catch (IOException e) {
            // Silently return null -- telemetry should never break the app
        }
        return null;
    }

    /**
     * Checks whether a UUID file exists and contains a valid UUID.
     */
    public static boolean exists() {
        return exists(getUuidPath());
    }

    /**
     * Checks whether a UUID file exists at the given path.
     */
    public static boolean exists(Path uuidPath) {
        return read(uuidPath) != null;
    }

    /**
     * Persists a UUID to disk, creating parent directories as needed.
     */
    private static void persist(Path uuidPath, String uuid) throws IOException {
        Files.createDirectories(uuidPath.getParent());
        Files.writeString(uuidPath, uuid + "\n");
    }

    /**
     * Validates that a string looks like a valid UUID.
     */
    static boolean isValidUuid(String value) {
        if (value == null || value.isBlank()) {
            return false;
        }
        try {
            UUID.fromString(value);
            return true;
        } catch (IllegalArgumentException e) {
            return false;
        }
    }
}
