package io.exoreaction.synthesis.telemetry;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Properties;

/**
 * Configuration for the Synthesis pilot telemetry system.
 *
 * <p>Telemetry is <b>mandatory</b> for all pilot installations. It cannot be disabled.
 * Configuration is stored globally at {@code ~/.synthesis/telemetry.properties}.
 *
 * <p>Configuration properties:
 * <ul>
 *   <li>{@code telemetry.slack.webhook_url} -- Slack incoming webhook URL for event reporting</li>
 *   <li>{@code telemetry.installed_at} -- Timestamp of first installation</li>
 * </ul>
 *
 * <p>Privacy: Telemetry sends ONLY operational metadata (command names, success/failure,
 * duration, OS, Java version). It never sends workspace content, filenames, credentials,
 * or user identity. See {@code docs/PILOT-LICENSE.md} for full details.
 */
public class TelemetryConfig {

    /** Global config file for telemetry settings. */
    public static final String CONFIG_FILENAME = "telemetry.properties";

    /** The default Slack webhook URL for Synthesis pilot telemetry. */
    // NOTE: This is a write-only incoming webhook. It can only post messages to the
    // configured Slack channel. It cannot read messages, list channels, or access any data.
    public static final String DEFAULT_WEBHOOK_URL = "https://hooks.slack.com/services/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";

    private String slackWebhookUrl;
    private String installedAt;

    /**
     * Creates a TelemetryConfig with default values.
     * Telemetry is always active -- there is no enable/disable toggle.
     */
    public TelemetryConfig() {
        this.slackWebhookUrl = DEFAULT_WEBHOOK_URL;
        this.installedAt = "";
    }

    // --- Getters and Setters ---

    public String getSlackWebhookUrl() {
        return slackWebhookUrl;
    }

    public void setSlackWebhookUrl(String slackWebhookUrl) {
        this.slackWebhookUrl = slackWebhookUrl;
    }

    public String getInstalledAt() {
        return installedAt;
    }

    public void setInstalledAt(String installedAt) {
        this.installedAt = installedAt;
    }

    /**
     * Returns whether telemetry can actually send events (webhook is configured).
     */
    public boolean isWebhookConfigured() {
        return slackWebhookUrl != null && !slackWebhookUrl.isBlank();
    }

    /**
     * Returns the path to the global telemetry config file.
     */
    public static Path getConfigPath() {
        return Path.of(System.getProperty("user.home"))
                .resolve(ClientUUID.GLOBAL_DIR)
                .resolve(CONFIG_FILENAME);
    }

    /**
     * Returns the config path under a custom home directory (for testing).
     */
    public static Path getConfigPath(Path homeDir) {
        return homeDir.resolve(ClientUUID.GLOBAL_DIR).resolve(CONFIG_FILENAME);
    }

    /**
     * Loads telemetry config from the global config file.
     * Returns default config if the file does not exist.
     */
    public static TelemetryConfig load() {
        return load(getConfigPath());
    }

    /**
     * Loads telemetry config from a specific path.
     */
    public static TelemetryConfig load(Path configPath) {
        TelemetryConfig config = new TelemetryConfig();

        if (!Files.exists(configPath)) {
            return config;
        }

        try {
            Properties props = new Properties();
            props.load(Files.newBufferedReader(configPath));

            config.slackWebhookUrl = props.getProperty("telemetry.slack.webhook_url", DEFAULT_WEBHOOK_URL);
            config.installedAt = props.getProperty("telemetry.installed_at", "");
        } catch (IOException e) {
            // Silently return defaults -- telemetry should never break the app
        }

        return config;
    }

    /**
     * Saves the telemetry config to the global config file.
     */
    public void save() throws IOException {
        save(getConfigPath());
    }

    /**
     * Saves the telemetry config to a specific path.
     */
    public void save(Path configPath) throws IOException {
        Files.createDirectories(configPath.getParent());

        String content = """
                # Synthesis Pilot Telemetry Configuration
                # Generated by: synthesis init
                #
                # Telemetry is mandatory for all pilot installations.
                # It sends ONLY operational metadata:
                #   - Client UUID (random, not linked to your identity)
                #   - Command name, success/failure, duration
                #   - OS name, Java version, Synthesis version
                #
                # Telemetry NEVER sends:
                #   - Workspace content, file names, or paths
                #   - API keys, credentials, or tokens
                #   - User identity, hostname, or IP address
                #
                # To see what is sent: run: synthesis telemetry --show
                # Full details: https://github.com/exoreaction/synthesis/blob/main/docs/PILOT-LICENSE.md

                telemetry.slack.webhook_url=%s
                telemetry.installed_at=%s
                """.formatted(slackWebhookUrl, installedAt);

        Files.writeString(configPath, content);
    }

    /**
     * Records the installation timestamp if not already set.
     */
    public void markInstalled() {
        if (installedAt == null || installedAt.isBlank()) {
            installedAt = Instant.now().toString();
        }
    }

    @Override
    public String toString() {
        return "TelemetryConfig{webhookConfigured=" + isWebhookConfigured()
                + ", installedAt=" + installedAt + "}";
    }
}
