package io.exoreaction.synthesis.analyzer;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDDocumentInformation;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for PresentationExtractor -- slide extraction, README generation,
 * and description parsing.
 */
class PresentationExtractorTest {

    @TempDir
    Path tempDir;

    private final PresentationExtractor extractor = new PresentationExtractor();

    @Test
    void testExtractSlidesBasic() throws IOException {
        Path pdfFile = createTestPresentation("test-deck.pdf", "Test Presentation", 5);
        Path outputDir = tempDir.resolve("output");

        PresentationExtractor.ExtractionResult result =
                extractor.extractSlides(pdfFile, outputDir, PresentationExtractor.DEFAULT_DPI, null);

        assertEquals(5, result.slidesExtracted());
        assertEquals(0, result.slidesDescribed(), "No AI client = no descriptions");
        assertEquals(5, result.slides().size());
        assertEquals("Test Presentation", result.presentationTitle());
        assertTrue(Files.exists(outputDir));

        // Verify slide images exist
        for (int i = 1; i <= 5; i++) {
            Path slideFile = outputDir.resolve(String.format("slide-%03d.png", i));
            assertTrue(Files.exists(slideFile), "Slide " + i + " should exist");
            assertTrue(Files.size(slideFile) > 0, "Slide " + i + " should not be empty");
        }
    }

    @Test
    void testExtractSlidesSinglePage() throws IOException {
        Path pdfFile = createTestPresentation("single.pdf", "Single Slide", 1);
        Path outputDir = tempDir.resolve("single-output");

        PresentationExtractor.ExtractionResult result =
                extractor.extractSlides(pdfFile, outputDir, PresentationExtractor.DEFAULT_DPI, null);

        assertEquals(1, result.slidesExtracted());
        assertEquals(1, result.slides().size());

        PresentationExtractor.SlideInfo slide = result.slides().get(0);
        assertEquals(1, slide.slideNumber());
        assertTrue(slide.description().isEmpty(), "No AI = no description");
        assertTrue(slide.keywords().isEmpty());
    }

    @Test
    void testExtractSlidesWithHighDpi() throws IOException {
        Path pdfFile = createTestPresentation("hires.pdf", "High Res", 2);
        Path outputDir = tempDir.resolve("hires-output");

        PresentationExtractor.ExtractionResult result =
                extractor.extractSlides(pdfFile, outputDir, PresentationExtractor.HIGH_DPI, null);

        assertEquals(2, result.slidesExtracted());

        // High DPI should produce larger files than default DPI
        Path slide1 = outputDir.resolve("slide-001.png");
        assertTrue(Files.size(slide1) > 0);
    }

    @Test
    void testGenerateReadme() throws IOException {
        Path pdfFile = createTestPresentation("deck.pdf", "My Deck", 3);
        Path outputDir = tempDir.resolve("readme-output");

        PresentationExtractor.ExtractionResult result =
                extractor.extractSlides(pdfFile, outputDir, PresentationExtractor.DEFAULT_DPI, null);

        String readme = extractor.generateReadme(result, pdfFile);

        assertTrue(readme.contains("# My Deck"));
        assertTrue(readme.contains("**Source:**"));
        assertTrue(readme.contains("**Slides:** 3"));
        assertTrue(readme.contains("## Slide 1"));
        assertTrue(readme.contains("## Slide 2"));
        assertTrue(readme.contains("## Slide 3"));
        assertTrue(readme.contains("slide-001.png"));
        assertTrue(readme.contains("Generated by Synthesis"));
    }

    @Test
    void testGenerateReadmeWithDescriptions() {
        // Create a result with descriptions
        List<PresentationExtractor.SlideInfo> slides = List.of(
                new PresentationExtractor.SlideInfo(1, Path.of("slide-001.png"),
                        "Title slide showing the company logo", List.of("title", "logo")),
                new PresentationExtractor.SlideInfo(2, Path.of("slide-002.png"),
                        "Architecture diagram with microservices", List.of("architecture", "microservices"))
        );

        PresentationExtractor.ExtractionResult result =
                new PresentationExtractor.ExtractionResult(
                        Path.of("output"), 2, 2, slides, "Tech Talk");

        String readme = extractor.generateReadme(result, Path.of("tech-talk.pdf"));

        assertTrue(readme.contains("**AI Descriptions:** 2 of 2 slides"));
        assertTrue(readme.contains("company logo"));
        assertTrue(readme.contains("Architecture diagram"));
        assertTrue(readme.contains("**Keywords:** title, logo"));
        assertTrue(readme.contains("**Keywords:** architecture, microservices"));
    }

    @Test
    void testEstimateCost() {
        assertEquals(0.20, PresentationExtractor.estimateCost(10), 0.001);
        assertEquals(1.00, PresentationExtractor.estimateCost(50), 0.001);
        assertEquals(0.02, PresentationExtractor.estimateCost(1), 0.001);
    }

    @Test
    void testParseDescription() {
        String response = """
                This slide shows a company overview with revenue charts.
                The main message is about Q4 growth.
                Keywords: revenue, growth, Q4, financial""";

        String desc = PresentationExtractor.parseDescription(response);
        assertTrue(desc.contains("company overview"));
        assertTrue(desc.contains("Q4 growth"));
        assertFalse(desc.contains("Keywords:"));
    }

    @Test
    void testParseDescriptionNoKeywords() {
        String response = "Simple description without keywords section.";
        assertEquals("Simple description without keywords section.",
                PresentationExtractor.parseDescription(response));
    }

    @Test
    void testParseDescriptionEmpty() {
        assertEquals("", PresentationExtractor.parseDescription(""));
        assertEquals("", PresentationExtractor.parseDescription(null));
    }

    @Test
    void testParseKeywords() {
        String response = """
                Description text here.
                Keywords: architecture, microservices, deployment, cloud""";

        List<String> keywords = PresentationExtractor.parseKeywords(response);
        assertEquals(4, keywords.size());
        assertTrue(keywords.contains("architecture"));
        assertTrue(keywords.contains("microservices"));
        assertTrue(keywords.contains("deployment"));
        assertTrue(keywords.contains("cloud"));
    }

    @Test
    void testParseKeywordsNoKeywordsLine() {
        List<String> keywords = PresentationExtractor.parseKeywords("Just a description.");
        assertTrue(keywords.isEmpty());
    }

    @Test
    void testParseKeywordsEmpty() {
        assertTrue(PresentationExtractor.parseKeywords("").isEmpty());
        assertTrue(PresentationExtractor.parseKeywords(null).isEmpty());
    }

    @Test
    void testParseKeywordsCaseInsensitive() {
        String response = "Desc.\nkeywords: Java, Spring Boot, REST API";
        List<String> keywords = PresentationExtractor.parseKeywords(response);
        assertEquals(3, keywords.size());
        assertTrue(keywords.contains("java"));
        assertTrue(keywords.contains("spring boot"));
        assertTrue(keywords.contains("rest api"));
    }

    @Test
    void testSlideNumbering() throws IOException {
        Path pdfFile = createTestPresentation("numbered.pdf", "Numbers", 3);
        Path outputDir = tempDir.resolve("numbered-output");

        PresentationExtractor.ExtractionResult result =
                extractor.extractSlides(pdfFile, outputDir, PresentationExtractor.DEFAULT_DPI, null);

        assertEquals(1, result.slides().get(0).slideNumber());
        assertEquals(2, result.slides().get(1).slideNumber());
        assertEquals(3, result.slides().get(2).slideNumber());
    }

    // --- Helper methods ---

    private Path createTestPresentation(String filename, String title, int slides) throws IOException {
        Path pdfFile = tempDir.resolve(filename);
        PDRectangle landscape = new PDRectangle(PDRectangle.A4.getHeight(), PDRectangle.A4.getWidth());

        try (PDDocument doc = new PDDocument()) {
            PDDocumentInformation info = doc.getDocumentInformation();
            info.setTitle(title);

            for (int i = 0; i < slides; i++) {
                PDPage page = new PDPage(landscape);
                doc.addPage(page);

                try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
                    cs.beginText();
                    cs.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 36);
                    cs.newLineAtOffset(200, 350);
                    cs.showText("Slide " + (i + 1));
                    cs.endText();

                    cs.beginText();
                    cs.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 18);
                    cs.newLineAtOffset(200, 300);
                    cs.showText("Content for slide " + (i + 1));
                    cs.endText();
                }
            }

            doc.save(pdfFile.toFile());
        }
        return pdfFile;
    }
}
