package io.exoreaction.synthesis.config;

import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.constructor.Constructor;
import org.yaml.snakeyaml.LoaderOptions;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;

/**
 * Loads and validates Synthesis workspace configuration.
 *
 * <p>Configuration hierarchy (later overrides earlier):
 * <ol>
 *   <li>Built-in defaults (hardcoded in {@link SynthesisConfig})</li>
 *   <li>Workspace config file ({@code .synthesis/config.yaml})</li>
 *   <li>Root config file ({@code synthesis-config.yaml} in workspace root)</li>
 * </ol>
 */
public final class ConfigLoader {

    /** Config file inside .synthesis directory. */
    public static final String INTERNAL_CONFIG = ".synthesis/config.yaml";

    /** Config file in workspace root (user-facing, convenient). */
    public static final String ROOT_CONFIG = "synthesis-config.yaml";

    private ConfigLoader() {}

    /**
     * Loads configuration for a workspace.
     * Searches for config files in priority order, falls back to defaults.
     *
     * @param workspaceRoot the workspace root directory
     * @return loaded and validated configuration
     */
    public static SynthesisConfig load(Path workspaceRoot) throws IOException {
        // Try root config first (user-visible, takes precedence)
        Path rootConfig = workspaceRoot.resolve(ROOT_CONFIG);
        if (Files.exists(rootConfig)) {
            return loadFromFile(rootConfig);
        }

        // Try internal config
        Path internalConfig = workspaceRoot.resolve(INTERNAL_CONFIG);
        if (Files.exists(internalConfig)) {
            return loadFromFile(internalConfig);
        }

        // Return defaults
        return new SynthesisConfig();
    }

    /**
     * Loads configuration from a specific YAML file.
     */
    public static SynthesisConfig loadFromFile(Path configFile) throws IOException {
        LoaderOptions options = new LoaderOptions();
        options.setAllowDuplicateKeys(false);
        Yaml yaml = new Yaml(new Constructor(SynthesisConfig.class, options));

        try (InputStream is = Files.newInputStream(configFile)) {
            SynthesisConfig config = yaml.load(is);
            return config != null ? config : new SynthesisConfig();
        }
    }

    /**
     * Generates default configuration YAML content for a new workspace.
     *
     * @param workspaceName name of the workspace
     * @param workspaceType type (e.g., "general", "plugin-ecosystem", "monorepo")
     * @return YAML content as a string
     */
    public static String generateDefaultConfig(String workspaceName, String workspaceType) {
        return generateDefaultConfig(workspaceName, workspaceType, null, null, 0, null);
    }

    /**
     * Generates configuration YAML content with workspace metadata.
     *
     * @param workspaceName    name of the workspace
     * @param workspaceType    legacy type (e.g., "general")
     * @param category         workspace category: source-code, documents, or mixed
     * @param primaryLanguage  primary programming language (may be null)
     * @param repoCount        number of repositories (0 if unknown)
     * @param company          owning company (may be null)
     * @return YAML content as a string
     */
    public static String generateDefaultConfig(String workspaceName, String workspaceType,
                                                String category, String primaryLanguage,
                                                int repoCount, String company) {
        StringBuilder sb = new StringBuilder();
        sb.append("""
                # Synthesis Workspace Configuration
                # Generated by: synthesis init

                workspace:
                  name: "%s"
                  type: "%s"
                  description: ""
                  metadata:
                    category: "%s"
                """.formatted(
                workspaceName,
                workspaceType,
                category != null ? category : "mixed"));

        if (primaryLanguage != null && !primaryLanguage.isBlank()) {
            sb.append("    primaryLanguage: \"").append(primaryLanguage).append("\"\n");
        }
        if (repoCount > 0) {
            sb.append("    repoCount: ").append(repoCount).append("\n");
        }
        if (company != null && !company.isBlank()) {
            sb.append("    company: \"").append(company).append("\"\n");
        }

        sb.append("""

                scan:
                  # File patterns to include in the index
                  includePatterns:
                    - "**/*.md"
                    - "**/*.java"
                    - "**/*.py"
                    - "**/*.js"
                    - "**/*.ts"
                    - "**/*.yaml"
                    - "**/*.yml"
                    - "**/*.json"
                    - "**/*.sh"
                    - "**/*.go"
                    - "**/*.rs"
                    - "**/*.kt"
                    - "**/*.sql"
                    - "**/*.txt"
                    - "**/*.pdf"

                  # Directories and patterns to exclude
                  excludePatterns:
                    - "**/node_modules/**"
                    - "**/.git/**"
                    - "**/target/**"
                    - "**/build/**"
                    - "**/__pycache__/**"
                    - "**/.venv/**"
                    - "**/.synthesis/**"

                  # Compute MD5 hashes for duplicate detection
                  computeHashes: true

                  # Skip files larger than this (bytes)
                  maxFileSizeBytes: 10485760

                search:
                  maxResults: 20
                  previewLength: 200
                  contentPreviewBytes: 10240

                ai:
                  # Set to true and provide ANTHROPIC_API_KEY to enable AI features
                  enabled: false
                  model: "claude-sonnet-4-5-20250929"
                  readmeGeneration: true
                  contentSummary: false
                  maxTokens: 1024
                """);

        return sb.toString();
    }

    /**
     * Validates a loaded configuration and returns any errors.
     *
     * @return empty if valid, error message if invalid
     */
    public static Optional<String> validate(SynthesisConfig config) {
        if (config.getWorkspace() == null) {
            return Optional.of("Missing 'workspace' section in configuration");
        }
        if (config.getScan() == null) {
            return Optional.of("Missing 'scan' section in configuration");
        }
        if (config.getScan().getMaxFileSizeBytes() <= 0) {
            return Optional.of("scan.maxFileSizeBytes must be positive");
        }
        if (config.getSearch() != null && config.getSearch().getMaxResults() <= 0) {
            return Optional.of("search.maxResults must be positive");
        }
        return Optional.empty();
    }
}
