package io.exoreaction.synthesis.config;

import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.constructor.Constructor;
import org.yaml.snakeyaml.LoaderOptions;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Loads and validates Synthesis workspace configuration.
 *
 * <p>Configuration hierarchy (later overrides earlier):
 * <ol>
 *   <li>Built-in defaults (hardcoded in {@link SynthesisConfig})</li>
 *   <li>Workspace config file ({@code .synthesis/config.yaml})</li>
 *   <li>Root config file ({@code synthesis-config.yaml} in workspace root)</li>
 * </ol>
 */
public final class ConfigLoader {

    /** Config file inside .synthesis directory. */
    public static final String INTERNAL_CONFIG = ".synthesis/config.yaml";

    /** Config file in workspace root (user-facing, convenient). */
    public static final String ROOT_CONFIG = "synthesis-config.yaml";

    private ConfigLoader() {}

    /**
     * Loads configuration for a workspace.
     * Searches for config files in priority order, falls back to defaults.
     *
     * @param workspaceRoot the workspace root directory
     * @return loaded and validated configuration
     */
    public static SynthesisConfig load(Path workspaceRoot) throws IOException {
        // Try root config first (user-visible, takes precedence)
        Path rootConfig = workspaceRoot.resolve(ROOT_CONFIG);
        if (Files.exists(rootConfig)) {
            return loadFromFile(rootConfig);
        }

        // Try internal config
        Path internalConfig = workspaceRoot.resolve(INTERNAL_CONFIG);
        if (Files.exists(internalConfig)) {
            return loadFromFile(internalConfig);
        }

        // Return defaults
        return new SynthesisConfig();
    }

    /**
     * Loads configuration from a specific YAML file.
     */
    public static SynthesisConfig loadFromFile(Path configFile) throws IOException {
        LoaderOptions options = new LoaderOptions();
        options.setAllowDuplicateKeys(false);
        Yaml yaml = new Yaml(new Constructor(SynthesisConfig.class, options));

        try (InputStream is = Files.newInputStream(configFile)) {
            SynthesisConfig config = yaml.load(is);
            return config != null ? config : new SynthesisConfig();
        }
    }

    /**
     * Generates default configuration YAML content for a new workspace.
     *
     * @param workspaceName name of the workspace
     * @param workspaceType type (e.g., "general", "plugin-ecosystem", "monorepo")
     * @return YAML content as a string
     */
    public static String generateDefaultConfig(String workspaceName, String workspaceType) {
        return generateDefaultConfig(workspaceName, workspaceType, null, null, 0, null);
    }

    /**
     * Generates configuration YAML content with workspace metadata.
     *
     * @param workspaceName    name of the workspace
     * @param workspaceType    legacy type (e.g., "general")
     * @param category         workspace category: source-code, documents, or mixed
     * @param primaryLanguage  primary programming language (may be null)
     * @param repoCount        number of repositories (0 if unknown)
     * @param company          owning company (may be null)
     * @return YAML content as a string
     */
    public static String generateDefaultConfig(String workspaceName, String workspaceType,
                                                String category, String primaryLanguage,
                                                int repoCount, String company) {
        StringBuilder sb = new StringBuilder();
        sb.append("""
                # Synthesis Workspace Configuration
                # Generated by: synthesis init

                workspace:
                  name: "%s"
                  type: "%s"
                  description: ""
                  metadata:
                    category: "%s"
                """.formatted(
                workspaceName,
                workspaceType,
                category != null ? category : "mixed"));

        if (primaryLanguage != null && !primaryLanguage.isBlank()) {
            sb.append("    primaryLanguage: \"").append(primaryLanguage).append("\"\n");
        }
        if (repoCount > 0) {
            sb.append("    repoCount: ").append(repoCount).append("\n");
        }
        if (company != null && !company.isBlank()) {
            sb.append("    company: \"").append(company).append("\"\n");
        }

        sb.append("""

                # report:
                #   outputDir: "reports"  # Custom report output directory
                #                         # Relative to workspace root, or absolute path
                #                         # Default: .synthesis/reports/

                scan:
                  # File patterns to include in the index
                  includePatterns:
                    - "**/*.md"
                    - "**/*.java"
                    - "**/*.py"
                    - "**/*.js"
                    - "**/*.ts"
                    - "**/*.yaml"
                    - "**/*.yml"
                    - "**/*.json"
                    - "**/*.sh"
                    - "**/*.go"
                    - "**/*.rs"
                    - "**/*.kt"
                    - "**/*.sql"
                    - "**/*.txt"
                    - "**/*.pdf"

                  # Directories and patterns to exclude
                  excludePatterns:
                    - "**/node_modules/**"
                    - "**/.git/**"
                    - "**/target/**"
                    - "**/build/**"
                    - "**/__pycache__/**"
                    - "**/.venv/**"
                    - "**/.synthesis/**"

                  # Compute MD5 hashes for duplicate detection
                  computeHashes: true

                  # Skip files larger than this (bytes)
                  maxFileSizeBytes: 10485760

                search:
                  maxResults: 20
                  previewLength: 200
                  contentPreviewBytes: 10240

                ai:
                  # Set to true and provide ANTHROPIC_API_KEY to enable AI features
                  enabled: false
                  model: "claude-sonnet-4-5-20250929"
                  readmeGeneration: true
                  contentSummary: false
                  maxTokens: 1024
                """);

        return sb.toString();
    }

    /**
     * Validates a loaded configuration and returns any errors.
     *
     * @return empty if valid, error message if invalid
     */
    public static Optional<String> validate(SynthesisConfig config) {
        if (config.getWorkspace() == null) {
            return Optional.of("Missing 'workspace' section in configuration");
        }
        if (config.getScan() == null) {
            return Optional.of("Missing 'scan' section in configuration");
        }
        if (config.getScan().getMaxFileSizeBytes() <= 0) {
            return Optional.of("scan.maxFileSizeBytes must be positive");
        }
        if (config.getSearch() != null && config.getSearch().getMaxResults() <= 0) {
            return Optional.of("search.maxResults must be positive");
        }

        // Validate sub-workspaces
        if (config.getSubWorkspaces() != null) {
            for (SynthesisConfig.SubWorkspaceConfig sw : config.getSubWorkspaces()) {
                if (sw.getName() == null || sw.getName().isBlank()) {
                    return Optional.of("Sub-workspace has empty name");
                }
                if (sw.getPath() == null || sw.getPath().isBlank()) {
                    return Optional.of("Sub-workspace '" + sw.getName() + "' has empty path");
                }
            }
        }

        return Optional.empty();
    }

    /**
     * Resolves the effective scan config for a sub-workspace by merging with parent config.
     *
     * <p>Inheritance rules:
     * <ul>
     *   <li>includePatterns: sub-workspace overrides parent if set, otherwise inherits</li>
     *   <li>excludePatterns: sub-workspace patterns are ADDED to parent patterns</li>
     *   <li>All other scan settings: inherited from parent (not overrideable per sub-workspace)</li>
     * </ul>
     *
     * @param parentScan the parent workspace's scan configuration
     * @param subWorkspace the sub-workspace configuration
     * @return effective scan config with inheritance applied
     */
    public static SynthesisConfig.ScanConfig resolveSubWorkspaceScanConfig(
            SynthesisConfig.ScanConfig parentScan,
            SynthesisConfig.SubWorkspaceConfig subWorkspace) {

        SynthesisConfig.ScanConfig resolved = new SynthesisConfig.ScanConfig();

        // Include patterns: override if set, otherwise inherit
        if (subWorkspace.getIncludePatterns() != null && !subWorkspace.getIncludePatterns().isEmpty()) {
            resolved.setIncludePatterns(subWorkspace.getIncludePatterns());
        } else {
            resolved.setIncludePatterns(parentScan.getIncludePatterns());
        }

        // Exclude patterns: merge (add sub-workspace patterns to parent patterns)
        List<String> mergedExcludes = new ArrayList<>(parentScan.getExcludePatterns());
        if (subWorkspace.getExcludePatterns() != null) {
            for (String pattern : subWorkspace.getExcludePatterns()) {
                if (!mergedExcludes.contains(pattern)) {
                    mergedExcludes.add(pattern);
                }
            }
        }
        resolved.setExcludePatterns(mergedExcludes);

        // Other settings: inherit from parent
        resolved.setComputeHashes(parentScan.isComputeHashes());
        resolved.setMaxFileSizeBytes(parentScan.getMaxFileSizeBytes());

        return resolved;
    }

    /**
     * Resolves which sub-workspace a file belongs to based on its relative path.
     *
     * <p>Matching algorithm:
     * <ol>
     *   <li>Check each sub-workspace's path prefix against the file's relative path</li>
     *   <li>Use the longest matching prefix (most specific match wins)</li>
     *   <li>Return null if no sub-workspace matches (file belongs to root workspace)</li>
     * </ol>
     *
     * @param relativePath the file's path relative to the workspace root
     * @param subWorkspaces the list of configured sub-workspaces
     * @return the matching sub-workspace name, or null if no match
     */
    public static String resolveSubWorkspace(String relativePath,
                                               List<SynthesisConfig.SubWorkspaceConfig> subWorkspaces) {
        if (subWorkspaces == null || subWorkspaces.isEmpty() || relativePath == null) {
            return null;
        }

        String bestMatch = null;
        int bestMatchLength = 0;

        for (SynthesisConfig.SubWorkspaceConfig sw : subWorkspaces) {
            String prefix = sw.getPath();
            if (prefix == null || prefix.isEmpty()) continue;

            // Normalize the prefix (ensure it ends with / for directory matching)
            String normalizedPrefix = prefix.endsWith("/") ? prefix : prefix + "/";

            // Check if the relative path starts with this prefix
            if (relativePath.startsWith(normalizedPrefix) || relativePath.equals(prefix)) {
                if (normalizedPrefix.length() > bestMatchLength) {
                    bestMatchLength = normalizedPrefix.length();
                    bestMatch = sw.getName();
                }
            }
        }

        return bestMatch;
    }
}
