package io.exoreaction.synthesis.skills;

import io.exoreaction.synthesis.org.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Templates for generating Claude Code skill YAML files.
 *
 * <p>Each template method generates a complete YAML skill file from
 * organizational data. Skills follow the Claude Code skill format:
 * <pre>
 *   name: skill-name
 *   version: 1.0.0
 *   description: What this skill provides
 *   auto_load: true
 *
 *   instructions: |
 *     Multi-line instructions for Claude...
 * </pre>
 *
 * <p>Generated skills are workspace-scoped (stored in .synthesis/skills/)
 * and can optionally be installed to ~/.claude/skills/ for global availability.
 */
public class SkillTemplate {

    private static final DateTimeFormatter TIMESTAMP_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
                    .withZone(ZoneId.systemDefault());

    private SkillTemplate() {} // utility class

    /**
     * Generates the workspace-context.yaml skill.
     * Provides overall workspace knowledge including all organizations.
     *
     * @param workspaceName  name of the workspace
     * @param workspaceRoot  root path of the workspace
     * @param organizations  all organizations in the workspace
     * @param timestamp      generation timestamp
     * @return YAML content for the skill file
     */
    public static String workspaceContext(String workspaceName, Path workspaceRoot,
                                          List<Organization> organizations, Instant timestamp) {
        StringBuilder sb = new StringBuilder();
        sb.append(yamlHeader("workspace-context",
                "Overall workspace knowledge (auto-generated by Synthesis)"));

        StringBuilder instructions = new StringBuilder();
        instructions.append(String.format(
                "You are working in the \"%s\" workspace (located at %s).%n%n",
                workspaceName, workspaceRoot));

        // Organizations summary
        instructions.append(String.format("**Organizations (%d):**%n", organizations.size()));
        for (Organization org : organizations) {
            instructions.append(String.format("- %s (%s)", org.getName(),
                    org.getType().name().toLowerCase()));
            List<String> details = new ArrayList<>();
            if (!org.getClients().isEmpty()) {
                details.add(org.getClients().size() + " clients");
            }
            if (!org.getProducts().isEmpty()) {
                details.add(org.getProducts().size() + " products");
            }
            if (!details.isEmpty()) {
                instructions.append(" - ").append(String.join(", ", details));
            }
            instructions.append("\n");
        }

        // Client summary across all orgs
        int totalClients = organizations.stream()
                .mapToInt(o -> o.getClients().size()).sum();
        int totalProducts = organizations.stream()
                .mapToInt(o -> o.getProducts().size()).sum();

        instructions.append(String.format("%n**Summary:**%n"));
        instructions.append(String.format("- Organizations: %d%n", organizations.size()));
        instructions.append(String.format("- Total clients: %d%n", totalClients));
        instructions.append(String.format("- Total products: %d%n", totalProducts));

        // Key files
        instructions.append(String.format("%n**Key Files:**%n"));
        instructions.append(String.format("- Organizations: %s/.synthesis/organizations.json%n", workspaceRoot));

        // Check for common important files
        Path activityLog = workspaceRoot.resolve("ACTIVITY-LOG.md");
        Path claudeMd = workspaceRoot.resolve("CLAUDE.md");
        if (activityLog.toFile().exists()) {
            instructions.append(String.format("- Activity Log: %s%n", activityLog));
        }
        if (claudeMd.toFile().exists()) {
            instructions.append(String.format("- Claude Instructions: %s%n", claudeMd));
        }

        instructions.append(String.format(
                "%nUse the organization-specific skills for detailed context.%n"));
        instructions.append(generatedFooter(timestamp));

        sb.append(formatInstructions(instructions.toString()));
        return sb.toString();
    }

    /**
     * Generates an organization-specific skill.
     *
     * @param org       the organization
     * @param timestamp generation timestamp
     * @return YAML content for the skill file
     */
    public static String organizationContext(Organization org, Instant timestamp) {
        String skillName = "organization-" + sanitizeForFilename(org.getName());
        StringBuilder sb = new StringBuilder();
        sb.append(yamlHeader(skillName,
                org.getName() + " " + org.getType().name().toLowerCase()
                        + " context (auto-generated by Synthesis)"));

        StringBuilder instructions = new StringBuilder();
        instructions.append(String.format("**%s** (%s)%n",
                org.getName(), org.getType().name()));
        instructions.append(String.format("Location: %s%n", org.getBasePath()));

        if (org.getDescription() != null && !org.getDescription().isEmpty()) {
            instructions.append(String.format("Description: %s%n", org.getDescription()));
        }

        // Active clients
        List<Client> active = org.getClientsByStatus(ClientStatus.ACTIVE);
        if (!active.isEmpty()) {
            instructions.append(String.format("%n**Active Clients (%d):**%n", active.size()));
            for (Client client : active) {
                instructions.append(formatClient(client));
            }
        }

        // Signed clients
        List<Client> signed = org.getClientsByStatus(ClientStatus.SIGNED);
        if (!signed.isEmpty()) {
            instructions.append(String.format("%n**Signed Clients (%d):**%n", signed.size()));
            for (Client client : signed) {
                instructions.append(formatClient(client));
            }
        }

        // Opportunity clients
        List<Client> opportunities = org.getClientsByStatus(ClientStatus.OPPORTUNITY);
        if (!opportunities.isEmpty()) {
            instructions.append(String.format("%n**Opportunity Clients (%d):**%n",
                    opportunities.size()));
            for (Client client : opportunities) {
                instructions.append(formatClient(client));
            }
        }

        // Past clients
        List<Client> past = org.getClientsByStatus(ClientStatus.PAST);
        if (!past.isEmpty()) {
            instructions.append(String.format("%n**Past Clients (%d):**%n", past.size()));
            for (Client client : past) {
                instructions.append(formatClient(client));
            }
        }

        // Products
        if (!org.getProducts().isEmpty()) {
            instructions.append(String.format("%n**Products (%d):**%n",
                    org.getProducts().size()));
            for (Product product : org.getProducts()) {
                instructions.append(String.format("- %s%n  Path: %s%n",
                        product.getName(), product.getBasePath()));
            }
        }

        // Codebase paths
        if (!org.getCodebasePaths().isEmpty()) {
            instructions.append(String.format("%n**Codebase Paths:**%n"));
            for (String path : org.getCodebasePaths()) {
                instructions.append(String.format("- %s%n", path));
            }
        }

        // Key files
        instructions.append(String.format("%n**Key Files:**%n"));
        Path orgPath = Path.of(org.getBasePath());
        if (orgPath.resolve("README.md").toFile().exists()) {
            instructions.append(String.format("- README: %s/README.md%n", org.getBasePath()));
        }
        if (orgPath.resolve("CODEBASE-INDEX.md").toFile().exists()) {
            instructions.append(String.format("- Codebase Index: %s/CODEBASE-INDEX.md%n",
                    org.getBasePath()));
        }
        // Check for business/PIPELINE-STATUS.md
        if (orgPath.resolve("business/PIPELINE-STATUS.md").toFile().exists()) {
            instructions.append(String.format("- Pipeline: %s/business/PIPELINE-STATUS.md%n",
                    org.getBasePath()));
        }
        // Check for PROOF-POINTS.md
        if (orgPath.resolve("PROOF-POINTS.md").toFile().exists()) {
            instructions.append(String.format("- Proof Points: %s/PROOF-POINTS.md%n",
                    org.getBasePath()));
        }

        instructions.append(generatedFooter(timestamp));

        sb.append(formatInstructions(instructions.toString()));
        return sb.toString();
    }

    /**
     * Generates the navigate-clients.yaml skill.
     * Provides quick client navigation shortcuts.
     *
     * @param organizations all organizations
     * @param timestamp     generation timestamp
     * @return YAML content for the skill file
     */
    public static String navigateClients(List<Organization> organizations, Instant timestamp) {
        StringBuilder sb = new StringBuilder();
        sb.append(yamlHeader("navigate-clients",
                "Client navigation shortcuts (auto-generated by Synthesis)"));

        StringBuilder instructions = new StringBuilder();
        instructions.append("**Quick Client Navigation:**\n\n");
        instructions.append("When user mentions a client, use these paths:\n\n");

        for (Organization org : organizations) {
            if (org.getClients().isEmpty()) continue;

            instructions.append(String.format("**%s Clients:**%n", org.getName()));
            for (Client client : org.getClients()) {
                instructions.append(String.format("- \"%s\" -> %s/%n",
                        client.getName(), client.getBasePath()));
            }
            instructions.append("\n");
        }

        instructions.append("Each client directory typically contains:\n");
        instructions.append("- README.md (client details, status, contacts)\n");
        instructions.append("- Correspondence, contracts, project notes\n");

        instructions.append(generatedFooter(timestamp));

        sb.append(formatInstructions(instructions.toString()));
        return sb.toString();
    }

    /**
     * Generates the pipeline-tracker.yaml skill.
     * Provides business pipeline awareness.
     *
     * @param organizations all organizations
     * @param timestamp     generation timestamp
     * @return YAML content for the skill file
     */
    public static String pipelineTracker(List<Organization> organizations, Instant timestamp) {
        StringBuilder sb = new StringBuilder();
        sb.append(yamlHeader("pipeline-tracker",
                "Business pipeline awareness (auto-generated by Synthesis)"));

        StringBuilder instructions = new StringBuilder();
        instructions.append("**Business Pipeline Overview:**\n\n");

        for (Organization org : organizations) {
            List<Client> signed = org.getClientsByStatus(ClientStatus.SIGNED);
            List<Client> active = org.getClientsByStatus(ClientStatus.ACTIVE);
            List<Client> opportunities = org.getClientsByStatus(ClientStatus.OPPORTUNITY);

            if (signed.isEmpty() && active.isEmpty() && opportunities.isEmpty()) continue;

            instructions.append(String.format("**%s:**%n", org.getName()));

            if (!signed.isEmpty()) {
                instructions.append(String.format("Signed (%d):%n", signed.size()));
                for (Client client : signed) {
                    instructions.append(String.format("- %s%n  Path: %s%n",
                            client.getName(), client.getBasePath()));
                }
            }

            if (!active.isEmpty()) {
                instructions.append(String.format("Active (%d):%n", active.size()));
                for (Client client : active) {
                    instructions.append(String.format("- %s%n  Path: %s%n",
                            client.getName(), client.getBasePath()));
                }
            }

            if (!opportunities.isEmpty()) {
                instructions.append(String.format("Opportunities (%d):%n",
                        opportunities.size()));
                for (Client client : opportunities) {
                    instructions.append(String.format("- %s%n  Path: %s%n",
                            client.getName(), client.getBasePath()));
                }
            }

            instructions.append("\n");
        }

        instructions.append("**When discussing revenue/pipeline:**\n");
        instructions.append("- Check organization business directories for PIPELINE-STATUS.md\n");
        instructions.append("- Weight by probability: Hot (50-70%), Warm (20-30%), Cold (<10%)\n");

        instructions.append(generatedFooter(timestamp));

        sb.append(formatInstructions(instructions.toString()));
        return sb.toString();
    }

    /**
     * Generates the proof-points.yaml skill.
     * Provides technical achievement awareness.
     *
     * @param organizations all organizations
     * @param timestamp     generation timestamp
     * @return YAML content for the skill file
     */
    public static String proofPoints(List<Organization> organizations, Instant timestamp) {
        StringBuilder sb = new StringBuilder();
        sb.append(yamlHeader("proof-points",
                "Technical achievements and proof points (auto-generated by Synthesis)"));

        StringBuilder instructions = new StringBuilder();
        instructions.append("**Technical Proof Points:**\n\n");

        for (Organization org : organizations) {
            boolean hasProof = !org.getProducts().isEmpty()
                    || !org.getCodebasePaths().isEmpty();
            if (!hasProof) continue;

            instructions.append(String.format("**%s:**%n", org.getName()));

            if (!org.getProducts().isEmpty()) {
                instructions.append("Products:\n");
                for (Product product : org.getProducts()) {
                    instructions.append(String.format("- %s%n  Path: %s%n",
                            product.getName(), product.getBasePath()));
                }
            }

            if (!org.getCodebasePaths().isEmpty()) {
                instructions.append("Codebases:\n");
                for (String path : org.getCodebasePaths()) {
                    instructions.append(String.format("- %s%n", path));
                }
            }

            // Check for PROOF-POINTS.md
            Path proofPoints = Path.of(org.getBasePath()).resolve("PROOF-POINTS.md");
            if (proofPoints.toFile().exists()) {
                instructions.append(String.format(
                        "%nFor full details see: %s%n", proofPoints));
            }

            instructions.append("\n");
        }

        instructions.append("**When discussing technical capability:**\n");
        instructions.append("- Lead with products (production systems) over proof-of-concept projects\n");
        instructions.append("- Check PROOF-POINTS.md for detailed metrics and achievements\n");
        instructions.append("- Reference specific codebases for technical credibility\n");

        instructions.append(generatedFooter(timestamp));

        sb.append(formatInstructions(instructions.toString()));
        return sb.toString();
    }

    /**
     * Generates the architecture-overview.yaml skill.
     * Provides high-level architecture knowledge from CODEBASE-INDEX.md
     * and directory structure analysis.
     *
     * @param organizations all organizations
     * @param timestamp     generation timestamp
     * @return YAML content for the skill file
     */
    public static String architectureOverview(List<Organization> organizations, Instant timestamp) {
        StringBuilder sb = new StringBuilder();
        sb.append(yamlHeader("architecture-overview",
                "High-level architecture overview (auto-generated by Synthesis)"));

        StringBuilder instructions = new StringBuilder();
        instructions.append("**Architecture Overview:**\n\n");
        instructions.append("When user asks about architecture, system design, or how things connect:\n\n");

        for (Organization org : organizations) {
            boolean hasArchInfo = !org.getCodebasePaths().isEmpty()
                    || !org.getProducts().isEmpty();
            if (!hasArchInfo) continue;

            instructions.append(String.format("**%s:**%n", org.getName()));

            // Products as architectural components
            if (!org.getProducts().isEmpty()) {
                instructions.append("Components:\n");
                for (Product product : org.getProducts()) {
                    instructions.append(String.format("- %s (%s)%n",
                            product.getName(), product.getBasePath()));
                }
            }

            // Codebases as source repositories
            if (!org.getCodebasePaths().isEmpty()) {
                instructions.append("Source Repositories:\n");
                int shown = 0;
                for (String path : org.getCodebasePaths()) {
                    if (shown >= MAX_LIST_ITEMS) {
                        instructions.append(String.format("  ... (+%d more)%n",
                                org.getCodebasePaths().size() - MAX_LIST_ITEMS));
                        break;
                    }
                    instructions.append(String.format("- %s%n", path));
                    shown++;
                }
            }

            // Check for CODEBASE-INDEX.md (architecture documentation)
            Path codebaseIndex = Path.of(org.getBasePath()).resolve("CODEBASE-INDEX.md");
            if (codebaseIndex.toFile().exists()) {
                instructions.append(String.format(
                        "Architecture Docs: %s%n", codebaseIndex));
            }

            instructions.append("\n");
        }

        instructions.append("**When discussing architecture:**\n");
        instructions.append("- Check CODEBASE-INDEX.md for repository structure and relationships\n");
        instructions.append("- Products represent deployable components\n");
        instructions.append("- Codebases represent source repositories (may contain multiple modules)\n");
        instructions.append("- See organization-specific skills for detailed context\n");

        instructions.append(generatedFooter(timestamp));

        sb.append(formatInstructions(instructions.toString()));
        return sb.toString();
    }

    /**
     * Generates the tech-stack.yaml skill.
     * Detects technologies from codebase paths and product directories.
     *
     * @param organizations all organizations
     * @param workspaceRoot workspace root path
     * @param timestamp     generation timestamp
     * @return YAML content for the skill file
     */
    public static String techStack(List<Organization> organizations, Path workspaceRoot,
                                    Instant timestamp) {
        StringBuilder sb = new StringBuilder();
        sb.append(yamlHeader("tech-stack",
                "Technologies and frameworks detected (auto-generated by Synthesis)"));

        StringBuilder instructions = new StringBuilder();
        instructions.append("**Technology Stack:**\n\n");
        instructions.append("Detected technologies across the workspace:\n\n");

        // Detect technologies by scanning for build files and common indicators
        Map<String, Set<String>> techByOrg = new LinkedHashMap<>();

        for (Organization org : organizations) {
            Set<String> technologies = detectTechnologies(org);
            if (!technologies.isEmpty()) {
                techByOrg.put(org.getName(), technologies);
            }
        }

        if (techByOrg.isEmpty()) {
            instructions.append("No technology indicators detected.\n");
            instructions.append("Scan codebases for build files (pom.xml, package.json, etc.) ");
            instructions.append("to enable technology detection.\n");
        } else {
            for (Map.Entry<String, Set<String>> entry : techByOrg.entrySet()) {
                instructions.append(String.format("**%s:**%n", entry.getKey()));
                for (String tech : entry.getValue()) {
                    instructions.append(String.format("- %s%n", tech));
                }
                instructions.append("\n");
            }
        }

        instructions.append("**When discussing technology choices:**\n");
        instructions.append("- Check build files (pom.xml, package.json) for exact versions\n");
        instructions.append("- Technologies are detected from project structure, not exhaustive\n");
        instructions.append("- See architecture-overview skill for component relationships\n");

        instructions.append(generatedFooter(timestamp));

        sb.append(formatInstructions(instructions.toString()));
        return sb.toString();
    }

    /**
     * Generates the key-decisions.yaml skill.
     * Provides awareness of important decision records if they exist.
     *
     * @param organizations all organizations
     * @param timestamp     generation timestamp
     * @return YAML content for the skill file
     */
    public static String keyDecisions(List<Organization> organizations, Instant timestamp) {
        StringBuilder sb = new StringBuilder();
        sb.append(yamlHeader("key-decisions",
                "Important decisions and strategic context (auto-generated by Synthesis)"));

        StringBuilder instructions = new StringBuilder();
        instructions.append("**Key Decisions and Strategic Context:**\n\n");
        instructions.append("When user asks about why something was done a certain way, ");
        instructions.append("check these locations for decision records:\n\n");

        boolean hasDecisionRecords = false;

        for (Organization org : organizations) {
            Path orgPath = Path.of(org.getBasePath());
            List<String> decisionFiles = new ArrayList<>();

            // Check for common decision record locations
            checkDecisionFile(orgPath, "docs/decisions", decisionFiles);
            checkDecisionFile(orgPath, "docs/adr", decisionFiles);
            checkDecisionFile(orgPath, "decisions", decisionFiles);
            checkDecisionFile(orgPath, "ADR", decisionFiles);
            checkDecisionFile(orgPath, "business/strategy", decisionFiles);

            // Check for specific important files
            Path analysisDir = orgPath.resolve("business").resolve("analysis");
            if (analysisDir.toFile().isDirectory()) {
                decisionFiles.add(analysisDir.toString());
            }

            if (!decisionFiles.isEmpty()) {
                hasDecisionRecords = true;
                instructions.append(String.format("**%s:**%n", org.getName()));
                for (String file : decisionFiles) {
                    instructions.append(String.format("- %s%n", file));
                }
                instructions.append("\n");
            }
        }

        if (!hasDecisionRecords) {
            instructions.append("No formal decision records (ADR/decision logs) detected.\n\n");
            instructions.append("Decision context may be found in:\n");
            instructions.append("- README.md files in project directories\n");
            instructions.append("- CLAUDE.md for project instructions and context\n");
            instructions.append("- Git commit messages for code decisions\n");
        }

        instructions.append("\n**When user asks 'why was this done this way?':**\n");
        instructions.append("- Check decision records listed above\n");
        instructions.append("- Look for README.md in the relevant directory\n");
        instructions.append("- Check git log for the related files\n");
        instructions.append("- Ask user if no documentation exists\n");

        instructions.append(generatedFooter(timestamp));

        sb.append(formatInstructions(instructions.toString()));
        return sb.toString();
    }

    // --- Technology detection helpers ---

    /** Maximum items to show in a list before truncating. */
    static final int MAX_LIST_ITEMS = 10;

    /**
     * Detects technologies used by an organization based on directory structure
     * and the presence of build/config files.
     */
    static Set<String> detectTechnologies(Organization org) {
        Set<String> technologies = new LinkedHashSet<>();
        Path orgPath = Path.of(org.getBasePath());

        // Check org directory itself
        detectTechFromPath(orgPath, technologies);

        // Check product directories
        for (Product product : org.getProducts()) {
            detectTechFromPath(Path.of(product.getBasePath()), technologies);
        }

        // Check codebase paths (just first level)
        for (String codebasePath : org.getCodebasePaths()) {
            Path path = Path.of(codebasePath);
            if (path.toFile().isDirectory()) {
                detectTechFromPath(path, technologies);
            }
        }

        return technologies;
    }

    /**
     * Detects technologies from a specific directory path
     * by checking for well-known build and configuration files.
     */
    private static void detectTechFromPath(Path dir, Set<String> technologies) {
        if (!dir.toFile().isDirectory()) return;

        // Java / JVM
        if (dir.resolve("pom.xml").toFile().exists()) {
            technologies.add("Java (Maven)");
        }
        if (dir.resolve("build.gradle").toFile().exists()
                || dir.resolve("build.gradle.kts").toFile().exists()) {
            technologies.add("Java/Kotlin (Gradle)");
        }

        // JavaScript / TypeScript
        if (dir.resolve("package.json").toFile().exists()) {
            technologies.add("JavaScript/TypeScript (Node.js)");
        }
        if (dir.resolve("tsconfig.json").toFile().exists()) {
            technologies.add("TypeScript");
        }

        // Python
        if (dir.resolve("requirements.txt").toFile().exists()
                || dir.resolve("setup.py").toFile().exists()
                || dir.resolve("pyproject.toml").toFile().exists()) {
            technologies.add("Python");
        }

        // Go
        if (dir.resolve("go.mod").toFile().exists()) {
            technologies.add("Go");
        }

        // Rust
        if (dir.resolve("Cargo.toml").toFile().exists()) {
            technologies.add("Rust");
        }

        // Docker
        if (dir.resolve("Dockerfile").toFile().exists()
                || dir.resolve("docker-compose.yaml").toFile().exists()
                || dir.resolve("docker-compose.yml").toFile().exists()) {
            technologies.add("Docker");
        }

        // Terraform / Infrastructure
        if (dir.resolve("main.tf").toFile().exists()) {
            technologies.add("Terraform");
        }

        // Kubernetes
        if (dir.resolve("k8s").toFile().isDirectory()
                || dir.resolve("kubernetes").toFile().isDirectory()) {
            technologies.add("Kubernetes");
        }
    }

    /**
     * Checks if a decision record directory exists and adds it to the list.
     */
    private static void checkDecisionFile(Path orgPath, String subPath, List<String> decisionFiles) {
        Path check = orgPath.resolve(subPath);
        if (check.toFile().isDirectory()) {
            decisionFiles.add(check.toString());
        }
    }

    // --- YAML formatting helpers ---

    /**
     * Generates the YAML header for a skill file.
     */
    static String yamlHeader(String name, String description) {
        return String.format(
                "name: %s%nversion: 1.0.0%ndescription: %s%nauto_load: true%n%n",
                name, description);
    }

    /**
     * Formats multi-line instructions as a YAML block scalar.
     * Uses the pipe (|) indicator for literal block scalar.
     */
    static String formatInstructions(String instructions) {
        StringBuilder sb = new StringBuilder("instructions: |\n");
        for (String line : instructions.split("\n", -1)) {
            if (line.isEmpty()) {
                sb.append("\n");
            } else {
                sb.append("  ").append(line).append("\n");
            }
        }
        return sb.toString();
    }

    /**
     * Formats a client entry for skill output.
     */
    static String formatClient(Client client) {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("- %s (%s)%n", client.getName(),
                client.getStatus().name()));
        sb.append(String.format("  Path: %s%n", client.getBasePath()));
        return sb.toString();
    }

    /**
     * Generates the footer line for generated skills.
     */
    static String generatedFooter(Instant timestamp) {
        return String.format(
                "%nThis skill was auto-generated by Synthesis on %s.%n" +
                "Source: .synthesis/organizations.json%n",
                TIMESTAMP_FORMAT.format(timestamp));
    }

    /**
     * Sanitizes a name for use as a filename.
     * Replaces spaces and special characters with hyphens.
     */
    public static String sanitizeForFilename(String name) {
        return name.toLowerCase()
                .replaceAll("[^a-z0-9-]", "-")
                .replaceAll("-+", "-")
                .replaceAll("^-|-$", "");
    }
}
