package io.exoreaction.synthesis.architecture;

import java.time.Instant;
import java.util.Map;

/**
 * An architecture alert detected by the {@link ArchitectureMonitor}.
 *
 * <p>Alerts represent potential architectural issues at varying severity levels.
 * They are generated by heuristic rules, graph analysis, and optionally AI analysis.
 *
 * @param severity    alert severity (ERROR, WARNING, INFO)
 * @param category    the type of anti-pattern detected
 * @param filePath    the file or module path related to the alert
 * @param message     human-readable description of the issue
 * @param metadata    additional structured data (metrics, thresholds, etc.)
 */
public record ArchitectureAlert(
        Severity severity,
        Category category,
        String filePath,
        String message,
        Map<String, Object> metadata
) {

    /**
     * Alert severity levels.
     */
    public enum Severity {
        /** Critical issue that should be fixed immediately. */
        ERROR,
        /** Significant issue that should be addressed. */
        WARNING,
        /** Informational finding that may or may not need action. */
        INFO
    }

    /**
     * Categories of architecture anti-patterns.
     */
    public enum Category {
        /** A dependency cycle exists between modules. */
        CIRCULAR_DEPENDENCY,
        /** A file is excessively large (too many lines or methods). */
        GOD_CLASS,
        /** A class references external code more than its own module. */
        FEATURE_ENVY,
        /** A change requires modifying many files. */
        SHOTGUN_SURGERY,
        /** A file has zero incoming references (potentially unused). */
        DEAD_CODE,
        /** A code module lacks documentation (no README). */
        MISSING_DOCUMENTATION,
        /** A source file has no corresponding test file. */
        TEST_COVERAGE_GAP,
        /** A file has too many incoming references (tight coupling). */
        HIGH_COUPLING,
        /** Custom AI-detected pattern. */
        AI_DETECTED
    }

    /**
     * Returns a single-line summary for CLI output.
     */
    public String toSummaryLine() {
        String prefix = switch (severity) {
            case ERROR -> "[ERROR]  ";
            case WARNING -> "[WARN]   ";
            case INFO -> "[INFO]   ";
        };
        return prefix + category.name() + " - " + filePath + ": " + message;
    }

    /**
     * Returns a JSON-compatible map representation.
     */
    public Map<String, Object> toMap() {
        return Map.of(
                "severity", severity.name(),
                "category", category.name(),
                "filePath", filePath,
                "message", message,
                "metadata", metadata
        );
    }
}
