package io.exoreaction.synthesis.kcp;

import org.yaml.snakeyaml.Yaml;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Generates governed {@code kind: skill} units (KCP v0.26 §4.3a) from a
 * repository's Claude Code skills ({@code .claude/skills/}), with a
 * fail-closed {@code action_scope} inferred from evidence in each skill's
 * own playbook (issue #477).
 *
 * <p>Units are emitted as a marker-delimited block appended to the {@code
 * units:} sequence of the repo's root {@code knowledge.yaml}. The block is
 * regenerable in place ({@link #mergeSkillsBlock}) and is preserved across
 * {@code kcp refresh} ({@link #stripSkillsBlock}). Because {@code kind:
 * skill} is a v0.26 feature, merging a non-empty block bumps the manifest's
 * {@code kcp_version} to 0.26.
 *
 * <p>Inference is deterministic and fail-closed: {@code tools} come from
 * what the playbook demonstrably invokes (shell fences → bash, git commands
 * → git; {@code read} always — a playbook must be read to be followed);
 * {@code paths} only from path-like tokens that exist in the repository,
 * emitted repo-root-relative; {@code capabilities} are never invented.
 * Absent an explicit eligibility grant a skill unit is selectable but not
 * invoke-eligible (§16.3 C4) — generated skills are discoverable but inert
 * until a human grants enactment.
 */
public final class KcpSkillScaffolder {

    public static final String BLOCK_BEGIN =
            "  # --- governed skills (generated by synthesis kcp skills) ---";
    public static final String BLOCK_END =
            "  # --- end governed skills ---";

    private static final int MAX_TRIGGERS = 8;
    private static final int MAX_PATHS = 8;

    private KcpSkillScaffolder() {
    }

    // -----------------------------------------------------------------------
    // Skill discovery
    // -----------------------------------------------------------------------

    /** One discovered skill: flat .yaml, flat .md, or a dir/SKILL.md. */
    public record SkillSource(String name, String relativePath, String intent,
                              List<String> triggers, String body) {}

    /**
     * Enumerates skills under {@code repoDir/.claude/skills}: flat
     * {@code *.yaml}/{@code *.yml} (name/description/trigger_phrases),
     * flat {@code *.md} (H1 as intent, headings as triggers), and
     * {@code <dir>/SKILL.md} subdirectory skills.
     */
    public static List<SkillSource> collectSkills(Path repoDir) {
        Path skillsDir = repoDir.resolve(".claude").resolve("skills");
        List<SkillSource> skills = new ArrayList<>();
        if (!Files.isDirectory(skillsDir)) return skills;
        try (Stream<Path> entries = Files.list(skillsDir)) {
            entries.sorted().forEach(entry -> {
                String fileName = entry.getFileName().toString();
                if (Files.isRegularFile(entry)
                        && (fileName.endsWith(".yaml") || fileName.endsWith(".yml"))) {
                    addYamlSkill(skills, repoDir, entry);
                } else if (Files.isRegularFile(entry) && fileName.endsWith(".md")) {
                    addMarkdownSkill(skills, repoDir, entry, stripExtension(fileName));
                } else if (Files.isDirectory(entry)) {
                    Path skillMd = entry.resolve("SKILL.md");
                    if (Files.isRegularFile(skillMd)) {
                        addMarkdownSkill(skills, repoDir, skillMd, fileName);
                    }
                }
            });
        } catch (Exception e) {
            // unreadable skills dir → no units; fail-closed, never partial-guess
        }
        return skills;
    }

    private static void addYamlSkill(List<SkillSource> skills, Path repoDir, Path file) {
        String content = readOrNull(file);
        if (content == null) return;
        Map<String, Object> parsed;
        try {
            Object loaded = new Yaml().load(content);
            if (!(loaded instanceof Map)) return;
            @SuppressWarnings("unchecked")
            Map<String, Object> map = (Map<String, Object>) loaded;
            parsed = map;
        } catch (Exception e) {
            return; // malformed skill file: skip, never guess
        }
        String name = str(parsed.get("name"));
        if (name == null || name.isBlank()) {
            name = stripExtension(file.getFileName().toString());
        }
        String intent = firstSentence(str(parsed.get("description")));
        if (intent == null) intent = "How do I use the " + name + " skill?";
        List<String> triggers = new ArrayList<>();
        if (parsed.get("trigger_phrases") instanceof List<?> phrases) {
            for (Object phrase : phrases) {
                String slugged = KcpScaffolder.slug(String.valueOf(phrase));
                if (!slugged.isBlank() && slugged.length() <= 40 && !triggers.contains(slugged)) {
                    triggers.add(slugged);
                }
                if (triggers.size() >= MAX_TRIGGERS) break;
            }
        }
        String body = content + "\n" + str(parsed.get("instructions"));
        skills.add(new SkillSource(name, relativize(repoDir, file), intent, triggers, body));
    }

    private static void addMarkdownSkill(List<SkillSource> skills, Path repoDir,
                                         Path file, String fallbackName) {
        String content = readOrNull(file);
        if (content == null) return;
        String name = fallbackName;
        String body = content;
        // Claude Code SKILL.md frontmatter: name/description between --- fences
        if (content.startsWith("---\n")) {
            int end = content.indexOf("\n---", 4);
            if (end > 0) {
                try {
                    Object loaded = new Yaml().load(content.substring(4, end));
                    if (loaded instanceof Map<?, ?> fm && fm.get("name") != null) {
                        name = String.valueOf(fm.get("name"));
                    }
                } catch (Exception e) {
                    // frontmatter unparseable: fall back to file-derived name
                }
                body = content.substring(end + 4);
            }
        }
        String intent = KcpScaffolder.firstHeadingOrSentence(body, relativize(repoDir, file));
        skills.add(new SkillSource(name, relativize(repoDir, file), intent,
                KcpScaffolder.headingTriggers(body), content));
    }

    // -----------------------------------------------------------------------
    // action_scope inference (deterministic, evidence-based, fail-closed)
    // -----------------------------------------------------------------------

    private static final Pattern SHELL_EVIDENCE = Pattern.compile(
            "```(?:bash|sh|shell|console)\\b|(?m)^\\s*\\$ |\\b(?:mvn|npx|npm|synthesis|java -jar)\\s");
    private static final Pattern GIT_EVIDENCE = Pattern.compile("\\bgit\\s+[a-z-]+");
    private static final Pattern PATH_TOKEN = Pattern.compile(
            "(?<![\\w@:/~-])((?:[A-Za-z0-9_.-]+/)+[A-Za-z0-9_.*-]+|[A-Za-z0-9_-]+\\.(?:xml|json|ya?ml|md|toml|properties|sql))");

    /** Tools the playbook demonstrably invokes; {@code read} always. */
    static List<String> inferTools(String body) {
        List<String> tools = new ArrayList<>();
        tools.add("read");
        if (body != null && SHELL_EVIDENCE.matcher(body).find()) tools.add("bash");
        if (body != null && GIT_EVIDENCE.matcher(body).find()) tools.add("git");
        return tools;
    }

    /**
     * Path-like tokens from the playbook that exist in the repository,
     * repo-root-relative, deduplicated, sorted, capped. Tokens that do not
     * resolve to a real file or directory are dropped — the envelope only
     * ever names evidence.
     */
    static List<String> inferPaths(Path repoDir, String body) {
        if (body == null) return List.of();
        Set<String> paths = new LinkedHashSet<>();
        Matcher matcher = PATH_TOKEN.matcher(body);
        while (matcher.find() && paths.size() < MAX_PATHS * 4) {
            String token = matcher.group(1).replaceAll("[.,;:!?]+$", "");
            if (token.contains("..") || token.startsWith("/") || token.startsWith("~")
                    || token.contains("*")) {
                continue;
            }
            try {
                if (Files.exists(repoDir.resolve(token))) {
                    paths.add(token);
                }
            } catch (Exception e) {
                // invalid path token on this filesystem: skip
            }
        }
        return paths.stream().sorted().limit(MAX_PATHS).toList();
    }

    // -----------------------------------------------------------------------
    // Emission
    // -----------------------------------------------------------------------

    /**
     * Renders the marker-delimited skills block for {@code skills}, or an
     * empty string when there are none. The block's items continue the
     * manifest's {@code units:} sequence (YAML comments do not break a
     * sequence), so it must be inserted while {@code units:} is still the
     * open top-level key — {@link #mergeSkillsBlock} handles that.
     */
    public static String skillsBlock(Path repoDir, List<SkillSource> skills) {
        if (skills.isEmpty()) return "";
        StringBuilder sb = new StringBuilder();
        String today = LocalDate.now().toString();
        sb.append(BLOCK_BEGIN).append("\n");
        sb.append("  # KCP v0.26 §4.3a — selectable like knowledge, enaction bounded by\n");
        sb.append("  # action_scope; not invoke-eligible without an explicit grant (§16.3 C4).\n");
        for (SkillSource skill : skills) {
            sb.append("  - id: ").append(KcpScaffolder.slug(skill.name())).append("\n");
            sb.append("    path: ").append(skill.relativePath()).append("\n");
            sb.append("    intent: \"").append(escape(skill.intent())).append("\"\n");
            sb.append("    scope: project\n");
            sb.append("    audience: [agent, operator]\n");
            sb.append("    kind: skill\n");
            sb.append("    validated: \"").append(today).append("\"\n");
            if (!skill.triggers().isEmpty()) {
                sb.append("    triggers: [").append(String.join(", ", skill.triggers()))
                        .append("]\n");
            }
            sb.append("    action_scope:\n");
            sb.append("      tools: [")
                    .append(String.join(", ", inferTools(skill.body()))).append("]\n");
            List<String> paths = inferPaths(repoDir, skill.body());
            if (!paths.isEmpty()) {
                sb.append("      paths: [\"")
                        .append(String.join("\", \"", paths)).append("\"]\n");
            }
            String hash = KcpScaffolder.sha256(repoDir.resolve(skill.relativePath()));
            if (hash != null) {
                sb.append("    content_hash:\n");
                sb.append("      algorithm: sha256\n");
                sb.append("      value: \"").append(hash).append("\"\n");
            }
            sb.append("    discovery:\n");
            sb.append("      verification_status: declared\n");
            sb.append("      source: synthesis\n");
            sb.append("\n");
        }
        sb.append(BLOCK_END).append("\n");
        return sb.toString();
    }

    // -----------------------------------------------------------------------
    // Manifest surgery
    // -----------------------------------------------------------------------

    /**
     * Replaces (or appends) the governed-skills block in {@code manifestYaml}.
     * The block is inserted before any top-level {@code signing:} block so the
     * {@code units:} sequence stays contiguous, and {@code kcp_version} is
     * bumped to 0.26 — {@code kind: skill} is a v0.26 feature. The
     * {@code hints.unit_count} is recomputed from the merged result. Passing
     * an empty block removes an existing one.
     */
    public static String mergeSkillsBlock(String manifestYaml, String block) {
        String base = stripSkillsBlock(manifestYaml);
        if (block == null || block.isBlank()) {
            return recountUnits(base);
        }
        if (!base.endsWith("\n")) base = base + "\n";

        String merged;
        int signingIdx = topLevelSigningIndex(base);
        if (signingIdx >= 0) {
            merged = base.substring(0, signingIdx) + block + base.substring(signingIdx);
        } else {
            merged = base + block;
        }
        merged = merged.replaceFirst("(?m)^kcp_version: \"0\\.2[0-9]\"$",
                "kcp_version: \"0.26\"");
        merged = merged.replaceFirst("\\(KCP\\) v0\\.2[0-9]", "(KCP) v0.26");
        return recountUnits(merged);
    }

    /** Removes the marker-delimited skills block, if present. */
    public static String stripSkillsBlock(String manifestYaml) {
        int begin = manifestYaml.indexOf(BLOCK_BEGIN);
        if (begin < 0) return manifestYaml;
        int end = manifestYaml.indexOf(BLOCK_END, begin);
        if (end < 0) return manifestYaml; // half a block: leave it for a human
        int endOfLine = manifestYaml.indexOf('\n', end);
        String tail = endOfLine < 0 ? "" : manifestYaml.substring(endOfLine + 1);
        return manifestYaml.substring(0, begin) + tail;
    }

    /** The skills block including markers, or null when absent. */
    public static String extractSkillsBlock(String manifestYaml) {
        int begin = manifestYaml.indexOf(BLOCK_BEGIN);
        if (begin < 0) return null;
        int end = manifestYaml.indexOf(BLOCK_END, begin);
        if (end < 0) return null;
        int endOfLine = manifestYaml.indexOf('\n', end);
        return manifestYaml.substring(begin,
                endOfLine < 0 ? manifestYaml.length() : endOfLine + 1);
    }

    /** Minimal standalone manifest used when a repo has no knowledge.yaml yet. */
    public static String standaloneManifest(Path repoDir, String synthesisVersion,
                                            String block) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by Synthesis ").append(synthesisVersion)
                .append(" — Knowledge Context Protocol (KCP) v0.26\n");
        sb.append("# Spec: github.com/cantara/knowledge-context-protocol\n");
        sb.append("kcp_version: \"0.26\"\n");
        sb.append("project: ").append(KcpScaffolder.slug(repoDir.getFileName().toString()))
                .append("\n");
        sb.append("version: 1.0.0\n");
        sb.append("updated: \"").append(LocalDate.now()).append("\"\n");
        sb.append("language: en\n");
        sb.append("indexing: open\n");
        sb.append("hints:\n");
        sb.append("  unit_count: 0\n");
        sb.append("  generated_by: synthesis@").append(synthesisVersion).append("\n");
        sb.append("\n");
        sb.append("units:\n");
        return recountUnits(sb + block);
    }

    private static String recountUnits(String manifestYaml) {
        int count = 0;
        for (String line : manifestYaml.split("\n")) {
            if (line.startsWith("  - id: ")) count++;
        }
        return manifestYaml.replaceFirst("(?m)^  unit_count: \\d+$",
                "  unit_count: " + count);
    }

    private static int topLevelSigningIndex(String manifestYaml) {
        int idx = 0;
        for (String line : manifestYaml.split("\n", -1)) {
            if (line.startsWith("signing:")) return idx;
            idx += line.length() + 1;
        }
        return -1;
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private static String relativize(Path repoDir, Path file) {
        return repoDir.relativize(file).toString().replace('\\', '/');
    }

    private static String stripExtension(String fileName) {
        int dot = fileName.lastIndexOf('.');
        return dot > 0 ? fileName.substring(0, dot) : fileName;
    }

    private static String str(Object value) {
        return value == null ? null : String.valueOf(value);
    }

    private static final Pattern SENTENCE_END = Pattern.compile("[.?!] ");

    private static String firstSentence(String text) {
        if (text == null || text.isBlank()) return null;
        String flat = text.strip().replace("\n", " ");
        Matcher end = SENTENCE_END.matcher(flat);
        String sentence = end.find() && end.start() < 160
                ? flat.substring(0, end.start() + 1) : flat;
        return sentence.length() > 200 ? sentence.substring(0, 200) : sentence;
    }

    private static String escape(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static String readOrNull(Path file) {
        try {
            return Files.readString(file);
        } catch (Exception e) {
            return null;
        }
    }
}
