package io.exoreaction.synthesis.kcp;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

/**
 * Scaffolds a KCP v0.25 {@code knowledge.yaml} from repository structure
 * (issue #357 / #310, Phase 4 of the v0.25 alignment epic).
 *
 * <p>Unlike {@code synthesis export --format kcp} (which reads the Lucene
 * index), the scaffolder works on any repository directory with no index:
 * it detects README/docs/policy markdown, Maven modules, CI workflows, and
 * test roots, and emits units with the same v0.25 evidence fields the
 * exporter produces (content_hash, content_structure, temporal.recorded_at,
 * discovery). Generated manifests carry {@code hints.generated_by:
 * synthesis@<version>} — the marker that authorises later automated refresh;
 * hand-authored manifests are never overwritten.
 */
public final class KcpScaffolder {

    private static final int MAX_DOC_UNITS = 20;
    private static final int MAX_TRIGGERS = 8;

    private KcpScaffolder() {
    }

    /**
     * Scaffolds a manifest for {@code repoDir}, or returns null when the
     * directory yields no units (nothing recognisable to describe).
     *
     * @param gitDates relative path → ISO committer date (empty outside git repos)
     */
    public static String scaffold(Path repoDir, String synthesisVersion,
                                  Map<String, String> gitDates) {
        List<Unit> units = collectUnits(repoDir);
        if (units.isEmpty()) return null;

        StringBuilder sb = new StringBuilder();
        String today = LocalDate.now().toString();
        sb.append("# Generated by Synthesis ").append(synthesisVersion)
                .append(" — Knowledge Context Protocol (KCP) v0.25\n");
        sb.append("# Spec: github.com/cantara/knowledge-context-protocol\n");
        sb.append("kcp_version: \"0.25\"\n");
        sb.append("project: ").append(slug(repoDir.getFileName().toString())).append("\n");
        sb.append("version: 1.0.0\n");
        sb.append("updated: \"").append(today).append("\"\n");
        sb.append("language: en\n");
        sb.append("indexing: open\n");
        sb.append("hints:\n");
        sb.append("  unit_count: ").append(units.size()).append("\n");
        sb.append("  generated_by: synthesis@").append(synthesisVersion).append("\n");
        sb.append("\n");
        sb.append("units:\n");
        for (Unit unit : units) {
            appendUnit(sb, unit, repoDir, gitDates);
        }
        return sb.toString();
    }

    // -----------------------------------------------------------------------
    // Unit detection
    // -----------------------------------------------------------------------

    private record Unit(String id, String relativePath, String intent, String scope,
                        String kind, boolean isDirectory, List<String> triggers) {}

    private static List<Unit> collectUnits(Path repoDir) {
        List<Unit> units = new ArrayList<>();

        // Root markdown: README + policy files
        addMarkdownUnit(units, repoDir, repoDir.resolve("README.md"), "global", null);
        for (String policy : new String[]{"SECURITY.md", "LICENSE.md", "CONTRIBUTING.md",
                "PRIVACY.md", "TERMS.md", "NOTICE.md"}) {
            addMarkdownUnit(units, repoDir, repoDir.resolve(policy), "global", "policy");
        }

        // docs/ markdown (two levels, capped)
        Path docs = repoDir.resolve("docs");
        if (Files.isDirectory(docs)) {
            try (Stream<Path> stream = Files.walk(docs, 2)) {
                stream.filter(p -> p.toString().endsWith(".md"))
                        .filter(Files::isRegularFile)
                        .sorted()
                        .limit(MAX_DOC_UNITS)
                        .forEach(p -> addMarkdownUnit(units, repoDir, p, "module", null));
            } catch (IOException e) {
                // skip docs on IO failure
            }
        }

        // Maven modules (multi-module pom) or single-module source root
        Path pom = repoDir.resolve("pom.xml");
        if (Files.isRegularFile(pom)) {
            List<String> modules = parseMavenModules(pom);
            if (!modules.isEmpty()) {
                for (String module : modules) {
                    if (Files.isDirectory(repoDir.resolve(module))) {
                        units.add(new Unit(slug(module), module,
                                "What does the " + module + " module contain?",
                                "module", null, true, List.of(slug(module), "module")));
                    }
                }
            } else if (Files.isDirectory(repoDir.resolve("src/main/java"))) {
                units.add(new Unit("source-root", "src/main/java",
                        "Where is the main source code?", "module", null, true,
                        List.of("source", "code", "implementation")));
            }
        }

        // CI workflows
        if (Files.isDirectory(repoDir.resolve(".github/workflows"))) {
            units.add(new Unit("ci", ".github/workflows",
                    "How is this repository built and released?", "module", null, true,
                    List.of("ci", "build", "release", "workflows")));
        }

        // Test root
        if (Files.isDirectory(repoDir.resolve("src/test"))) {
            units.add(new Unit("tests", "src/test",
                    "Where are the tests and how are they organised?", "module", null, true,
                    List.of("tests", "testing", "junit")));
        }

        return units;
    }

    private static void addMarkdownUnit(List<Unit> units, Path repoDir, Path file,
                                        String scope, String kind) {
        if (!Files.isRegularFile(file)) return;
        String relative = repoDir.relativize(file).toString().replace('\\', '/');
        String content = readOrNull(file);
        String intent = firstHeadingOrSentence(content, relative);
        List<String> triggers = headingTriggers(content);
        units.add(new Unit(slug(stripExtension(relative)), relative, intent, scope,
                kind, false, triggers));
    }

    // -----------------------------------------------------------------------
    // Emission
    // -----------------------------------------------------------------------

    private static void appendUnit(StringBuilder sb, Unit unit, Path repoDir,
                                   Map<String, String> gitDates) {
        sb.append("  - id: ").append(unit.id()).append("\n");
        sb.append("    path: ").append(unit.relativePath()).append("\n");
        sb.append("    intent: \"").append(escape(unit.intent())).append("\"\n");
        sb.append("    scope: ").append(unit.scope()).append("\n");
        sb.append("    audience: [human, agent]\n");
        if (!unit.isDirectory()) {
            sb.append("    format: markdown\n");
        }
        if (unit.kind() != null) {
            sb.append("    kind: ").append(unit.kind()).append("\n");
        }
        Path abs = repoDir.resolve(unit.relativePath());
        sb.append("    validated: \"").append(lastModified(abs)).append("\"\n");
        if (!unit.triggers().isEmpty()) {
            sb.append("    triggers: [").append(String.join(", ", unit.triggers())).append("]\n");
        }
        sb.append("    content_structure:\n");
        sb.append("      primary: ").append(unit.isDirectory() ? "reference" : "prose").append("\n");
        sb.append("      contains: [").append(unit.isDirectory() ? "reference" : "prose").append("]\n");
        if (!unit.isDirectory()) {
            String hash = sha256(abs);
            if (hash != null) {
                sb.append("    content_hash:\n");
                sb.append("      algorithm: sha256\n");
                sb.append("      value: \"").append(hash).append("\"\n");
            }
        }
        String recordedAt = gitDates.get(unit.relativePath());
        if (recordedAt != null) {
            sb.append("    temporal:\n");
            sb.append("      recorded_at: \"").append(recordedAt).append("\"\n");
        }
        sb.append("    discovery:\n");
        sb.append("      verification_status: declared\n");
        sb.append("      source: synthesis\n");
        sb.append("\n");
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /** Extracts <module> entries from a Maven pom (XML comments stripped first). */
    static List<String> parseMavenModules(Path pom) {
        String content = readOrNull(pom);
        if (content == null) return List.of();
        content = content.replaceAll("(?s)<!--.*?-->", "");
        List<String> modules = new ArrayList<>();
        var matcher = java.util.regex.Pattern.compile("<module>\\s*([^<]+?)\\s*</module>")
                .matcher(content);
        while (matcher.find()) {
            modules.add(matcher.group(1).trim());
        }
        return modules;
    }

    /** First markdown heading text, else the first sentence, else a fallback question. */
    static String firstHeadingOrSentence(String content, String relativePath) {
        if (content != null) {
            for (String line : content.split("\n")) {
                if (line.startsWith("#")) {
                    String heading = line.replaceAll("^#+\\s*", "").trim();
                    if (!heading.isBlank()) return heading;
                }
            }
            String trimmed = content.strip();
            if (!trimmed.isBlank()) {
                int dot = trimmed.indexOf(". ");
                String sentence = dot > 0 && dot < 120 ? trimmed.substring(0, dot + 1)
                        : trimmed.substring(0, Math.min(trimmed.length(), 120));
                if (!sentence.isBlank()) return sentence.replace("\n", " ");
            }
        }
        return "What does " + relativePath + " document?";
    }

    static List<String> headingTriggers(String content) {
        List<String> triggers = new ArrayList<>();
        if (content == null) return triggers;
        for (String line : content.split("\n")) {
            if (!line.startsWith("#")) continue;
            String slugged = slug(line.replaceAll("^#+\\s*", ""));
            if (!slugged.isBlank() && slugged.length() <= 40 && !triggers.contains(slugged)) {
                triggers.add(slugged);
            }
            if (triggers.size() >= MAX_TRIGGERS) break;
        }
        return triggers;
    }

    public static String slug(String text) {
        return text.toLowerCase()
                .replaceAll("[/\\\\\\s]+", "-")
                .replaceAll("[^a-z0-9\\-.]", "-")
                .replaceAll("-{2,}", "-")
                .replaceAll("(^-+|-+$)", "");
    }

    private static String stripExtension(String path) {
        int dot = path.lastIndexOf('.');
        int slash = path.lastIndexOf('/');
        return dot > slash ? path.substring(0, dot) : path;
    }

    private static String escape(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static String readOrNull(Path file) {
        try {
            return Files.readString(file);
        } catch (Exception e) {
            return null;
        }
    }

    private static String lastModified(Path file) {
        try {
            return LocalDate.ofInstant(Files.getLastModifiedTime(file).toInstant(),
                    ZoneId.systemDefault()).toString();
        } catch (Exception e) {
            return LocalDate.now().toString();
        }
    }

    static String sha256(Path file) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            StringBuilder hex = new StringBuilder();
            for (byte b : md.digest(Files.readAllBytes(file))) {
                hex.append(String.format("%02x", b));
            }
            return hex.toString();
        } catch (Exception e) {
            return null;
        }
    }

    /** True when the manifest carries the Synthesis generation marker. */
    public static boolean isSynthesisGenerated(String manifestYaml) {
        return manifestYaml != null && manifestYaml.contains("generated_by: synthesis@");
    }

    /**
     * Strips volatile lines (dates, hashes, generator version) so two scaffolds
     * of the same repo structure compare equal regardless of when they were
     * generated. Used by refresh to detect structural hand-edits: if the
     * normalized existing manifest differs from a normalized fresh scaffold,
     * a human changed more than Synthesis maintains — never overwrite then.
     */
    public static String normalizeVolatile(String manifestYaml) {
        StringBuilder sb = new StringBuilder();
        boolean skipNextValueLine = false;
        for (String line : manifestYaml.split("\n", -1)) {
            String stripped = line.strip();
            if (skipNextValueLine && stripped.startsWith("recorded_at:")) {
                skipNextValueLine = false;
                continue;
            }
            skipNextValueLine = false;
            if (stripped.startsWith("# Generated by Synthesis")
                    || stripped.startsWith("updated:")
                    || stripped.startsWith("validated:")
                    || stripped.startsWith("generated_by:")
                    || stripped.startsWith("value:")           // content_hash value
                    || stripped.startsWith("recorded_at:")) {
                continue;
            }
            if (stripped.equals("temporal:")) {
                // temporal block currently holds only recorded_at — drop both lines
                skipNextValueLine = true;
                continue;
            }
            sb.append(line).append("\n");
        }
        return sb.toString();
    }
}
