package io.exoreaction.synthesis.cli;

import io.exoreaction.synthesis.SynthesisApp;
import io.exoreaction.synthesis.config.ConfigLoader;
import io.exoreaction.synthesis.config.SynthesisConfig;
import io.exoreaction.synthesis.core.ScanState;
import io.exoreaction.synthesis.core.WorkspaceManager;
import io.exoreaction.synthesis.db.SynthesisDatabase;
import io.exoreaction.synthesis.graph.SecurityPosture;
import io.exoreaction.synthesis.index.SearchIndex;
import io.exoreaction.synthesis.util.AnsiOutput;
import io.exoreaction.synthesis.util.FileUtils;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.ParentCommand;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.concurrent.Callable;
import java.util.stream.Stream;

/**
 * Maintains a fresh Synthesis Stats section in a CLAUDE.md file.
 *
 * <p>Uses marker comments to identify the managed section, so only the
 * Synthesis-owned content is touched. Solves the KCP "validated" staleness
 * problem by auto-updating numbers.
 *
 * <p>Usage:
 * <pre>
 *   synthesis claude-md refresh                       # Update ./CLAUDE.md
 *   synthesis claude-md refresh -f /path/to/CLAUDE.md # Specific file
 *   synthesis claude-md refresh --dry-run             # Print result without modifying
 *   synthesis claude-md refresh --section-title "Codebase Stats"
 * </pre>
 */
@Command(
        name = "claude-md",
        description = "Maintain Synthesis Stats section in CLAUDE.md",
        mixinStandardHelpOptions = true,
        subcommands = {
                ClaudeMdCommand.RefreshSubcommand.class
        }
)
public class ClaudeMdCommand implements Callable<Integer> {

    @ParentCommand
    private SynthesisApp parent;

    // Package-private setter for testing
    void setParent(SynthesisApp parent) { this.parent = parent; }

    @Override
    public Integer call() {
        System.out.println("Usage: synthesis claude-md refresh [options]");
        System.out.println();
        System.out.println("Subcommands:");
        System.out.println("  refresh    Update Synthesis Stats section in CLAUDE.md");
        return 0;
    }

    /**
     * The 'synthesis claude-md refresh' subcommand.
     */
    @Command(
            name = "refresh",
            description = "Update Synthesis Stats section in CLAUDE.md",
            mixinStandardHelpOptions = true
    )
    public static class RefreshSubcommand implements Callable<Integer> {

        @ParentCommand
        private ClaudeMdCommand parent;

        @Option(names = {"-f", "--file"}, description = "Path to CLAUDE.md (default: ./CLAUDE.md)")
        private Path file;

        @Option(names = {"--dry-run"}, description = "Print result to stdout without modifying the file",
                defaultValue = "false")
        private boolean dryRun;

        @Option(names = {"--section-title"}, description = "Title of the managed section (default: Synthesis Stats)",
                defaultValue = "Synthesis Stats")
        private String sectionTitle = "Synthesis Stats";

        static final String MARKER_START = "<!-- synthesis-stats:start -->";
        static final String MARKER_END = "<!-- synthesis-stats:end -->";

        // Package-private setters for testing
        void setParent(ClaudeMdCommand parent) { this.parent = parent; }
        void setFile(Path file) { this.file = file; }
        void setDryRun(boolean dryRun) { this.dryRun = dryRun; }
        void setSectionTitle(String sectionTitle) { this.sectionTitle = sectionTitle; }

        @Override
        public Integer call() {
            try {
                Path workspaceRoot = parent.parent != null ? parent.parent.getWorkspaceRoot()
                        : Path.of(".").toAbsolutePath().normalize();

                // Determine file path
                Path claudeMdPath = file;
                if (claudeMdPath == null) {
                    claudeMdPath = Path.of(".").toAbsolutePath().normalize().resolve("CLAUDE.md");
                }

                // Generate the managed section content
                String statsContent = generateStatsContent(workspaceRoot);

                // Build full managed section
                String managedSection = MARKER_START + "\n" +
                        "## " + sectionTitle + "\n" +
                        "*Auto-generated by `synthesis claude-md refresh` -- do not edit manually*\n" +
                        "\n" +
                        statsContent +
                        MARKER_END;

                // Read existing file or create new
                String existingContent = "";
                if (Files.exists(claudeMdPath)) {
                    existingContent = Files.readString(claudeMdPath);
                }

                String result;
                if (existingContent.isEmpty()) {
                    // Create new file with just the managed section
                    result = managedSection + "\n";
                } else {
                    // Check for markers
                    int startIdx = existingContent.indexOf(MARKER_START);
                    int endIdx = existingContent.indexOf(MARKER_END);

                    if (startIdx >= 0 && endIdx >= 0 && endIdx > startIdx) {
                        // Replace existing managed section
                        result = existingContent.substring(0, startIdx) +
                                managedSection +
                                existingContent.substring(endIdx + MARKER_END.length());
                    } else if (startIdx >= 0 && endIdx < 0) {
                        // Start marker without end marker -- malformed
                        AnsiOutput.printError("Malformed markers in " + claudeMdPath +
                                ": found start marker but no matching end marker.");
                        AnsiOutput.printError("File will not be modified. Fix the markers manually first.");
                        return 1;
                    } else if (startIdx < 0 && endIdx >= 0) {
                        // End marker without start marker -- malformed
                        AnsiOutput.printError("Malformed markers in " + claudeMdPath +
                                ": found end marker but no matching start marker.");
                        AnsiOutput.printError("File will not be modified. Fix the markers manually first.");
                        return 1;
                    } else {
                        // No markers -- append to end
                        String separator = existingContent.endsWith("\n") ? "\n" : "\n\n";
                        result = existingContent + separator + managedSection + "\n";
                    }
                }

                if (dryRun) {
                    System.out.print(result);
                    return 0;
                }

                // Write result
                Files.createDirectories(claudeMdPath.getParent());
                Files.writeString(claudeMdPath, result);
                AnsiOutput.printSuccess("Updated " + claudeMdPath);

                return 0;

            } catch (Exception e) {
                AnsiOutput.printError("claude-md refresh failed: " + e.getMessage());
                return 1;
            }
        }

        /**
         * Generates the stats content as a markdown table.
         */
        String generateStatsContent(Path workspaceRoot) {
            StringBuilder sb = new StringBuilder();
            sb.append("| Metric | Value |\n");
            sb.append("|--------|-------|\n");

            // File count and index size
            int fileCount = 0;
            long indexSize = 0;
            try {
                WorkspaceManager workspace = new WorkspaceManager(workspaceRoot);
                Path indexPath = workspace.getIndexPath();
                if (Files.exists(indexPath) && hasIndexFiles(indexPath)) {
                    try (SearchIndex index = SearchIndex.openReadOnly(indexPath)) {
                        fileCount = index.documentCount();
                    }
                    indexSize = getDirectorySize(indexPath);
                }
            } catch (Exception e) {
                // Skip index stats
            }
            sb.append("| Files indexed | ").append(String.format("%,d", fileCount)).append(" |\n");
            sb.append("| Index size | ").append(FileUtils.formatSize(indexSize)).append(" |\n");

            // Last scan time
            try {
                WorkspaceManager workspace = new WorkspaceManager(workspaceRoot);
                Path scanStatePath = workspace.getScanStatePath();
                if (ScanState.exists(scanStatePath)) {
                    ScanState scanState = ScanState.load(scanStatePath);
                    Instant scanTime = scanState.getLastScanTime();
                    String lastScanStr = LocalDateTime.ofInstant(scanTime, ZoneId.systemDefault())
                            .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
                    Duration elapsed = Duration.between(scanTime, Instant.now());
                    sb.append("| Last scan | ").append(lastScanStr)
                            .append(" (").append(formatDuration(elapsed)).append(" ago) |\n");
                }
            } catch (Exception e) {
                // Skip scan time
            }

            // Security posture
            try {
                SynthesisDatabase db = SynthesisDatabase.getDefault();
                SecurityPosture security = SecurityPosture.query(
                        db.getConnection(), workspaceRoot.toString());
                if (!security.noData() && security.totalCount() > 0) {
                    sb.append("| Security posture | ")
                            .append(security.highCount()).append(" HIGH \u00B7 ")
                            .append(security.mediumCount()).append(" MEDIUM \u00B7 ")
                            .append(security.lowCount()).append(" LOW |\n");
                }
            } catch (Exception e) {
                // Skip security
            }

            sb.append("\n");
            return sb.toString();
        }

        private String formatDuration(Duration duration) {
            long seconds = duration.getSeconds();
            if (seconds < 60) return seconds + "s";
            long minutes = duration.toMinutes();
            if (minutes < 60) return minutes + " min";
            long hours = duration.toHours();
            if (hours < 24) return hours + "h " + (minutes % 60) + "m";
            long days = hours / 24;
            return days + " day" + (days > 1 ? "s" : "");
        }

        private boolean hasIndexFiles(Path indexPath) {
            try (Stream<Path> stream = Files.list(indexPath)) {
                return stream.findAny().isPresent();
            } catch (IOException e) {
                return false;
            }
        }

        private long getDirectorySize(Path dir) {
            try (Stream<Path> stream = Files.walk(dir)) {
                return stream.filter(Files::isRegularFile)
                        .mapToLong(path -> {
                            try { return Files.size(path); }
                            catch (IOException e) { return 0; }
                        })
                        .sum();
            } catch (IOException e) {
                return 0;
            }
        }
    }
}
